/**
 * Generate plugin-types/index.d.ts from src/client/PluginApi.ts
 *
 * This script extracts type definitions from the source code and generates
 * a standalone .d.ts file for external plugin developers.
 */

const ts = require('typescript');
const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const SOURCE_FILE = path.join(PROJECT_ROOT, 'src', 'client', 'PluginApi.ts');
const OUTPUT_FILE = path.join(__dirname, 'index.d.ts');
const TSCONFIG_PATH = path.join(PROJECT_ROOT, 'tsconfig.json');

console.log('🔧 Generating plugin types from source...');
console.log(`📄 Source: ${path.relative(PROJECT_ROOT, SOURCE_FILE)}`);
console.log(`📝 Output: ${path.relative(PROJECT_ROOT, OUTPUT_FILE)}`);

// Read tsconfig
const configFile = ts.readConfigFile(TSCONFIG_PATH, ts.sys.readFile);
const parsedConfig = ts.parseJsonConfigFileContent(
  configFile.config,
  ts.sys,
  PROJECT_ROOT
);

// Create program
const program = ts.createProgram({
  rootNames: [SOURCE_FILE],
  options: {
    ...parsedConfig.options,
    declaration: true,
    emitDeclarationOnly: true,
    declarationDir: path.join(__dirname, '.temp'),
    noEmit: false
  }
});

const sourceFile = program.getSourceFile(SOURCE_FILE);
if (!sourceFile) {
  console.error('❌ Could not load source file');
  process.exit(1);
}

const checker = program.getTypeChecker();
const output = [];

// Header comment
output.push(`/**
 * TypeScript Type Definitions for Arkadia Web Client Plugins
 *
 * This package provides TypeScript type definitions for developing
 * plugins for the Arkadia Web Client.
 *
 * MAINTAINER NOTE: This file is AUTO-GENERATED from src/client/PluginApi.ts
 * Do not edit this file directly. Run 'yarn build:types' to regenerate.
 *
 * @packageDocumentation
 */
`);

// Track what we've already exported to avoid duplicates
const exportedTypes = new Set();

// Helper to get JSDoc comments
function getJsDocComments(node) {
  const fullText = node.getFullText();
  const jsDocRegex = /\/\*\*[\s\S]*?\*\//g;
  const matches = fullText.match(jsDocRegex);
  return matches ? matches[matches.length - 1] : null;
}

// Helper to check if a type should be exported: every interface and type
// alias PluginApi.ts exports is part of the public API (anything a signature
// references must be importable by plugins), except implementation details.
function shouldExport(node) {
  if (!ts.isInterfaceDeclaration(node) && !ts.isTypeAliasDeclaration(node)) {
    return false;
  }
  const isExported = node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
  const name = node.name?.text;
  return Boolean(isExported && name && !name.includes('Impl') && !name.includes('Internal'));
}

// Helper to get JSDoc comments (only the leading JSDoc before the node)
function getLeadingJsDoc(node, file = sourceFile) {
  const fullText = node.getFullText(file);
  const nodeText = node.getText(file);
  const leading = fullText.substring(0, fullText.indexOf(nodeText));

  // Extract the JSDoc comment (/** ... */) closest to the declaration
  const jsDocMatches = leading.match(/\/\*\*[\s\S]*?\*\//g);
  return jsDocMatches ? jsDocMatches[jsDocMatches.length - 1] : null;
}

// Helper to convert node to string
function nodeToString(node, file = sourceFile) {
  const printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed,
    removeComments: false  // Keep comments for interface members
  });

  let result = printer.printNode(ts.EmitHint.Unspecified, node, file);

  // Remove all leading comments (JSDoc is added separately, and a stray line
  // comment left in front would end up between 'export' and the declaration)
  result = result.replace(/^(?:\s*(?:\/\/[^\n]*(?:\n|$)|\/\*[\s\S]*?\*\/))+\s*/, '');

  // Remove 'export ' / 'declare ' keywords if present (TypeScript printer adds them)
  result = result.replace(/^export\s+/, '').replace(/^declare\s+/, '');

  return result;
}

// Emit a single interface / type alias declaration with its JSDoc
function emitDeclaration(node, file = sourceFile) {
  const jsDoc = getLeadingJsDoc(node, file);
  if (jsDoc) {
    output.push('\n' + jsDoc);
  }
  output.push('\nexport ' + nodeToString(node, file));
  emittedNodes.push(node);
}

// Declarations emitted from source (scanned later for external references)
const emittedNodes = [];

// Process the source file
function processNode(node) {
  if (shouldExport(node)) {
    const name = node.name?.text;
    if (name && !exportedTypes.has(name)) {
      exportedTypes.add(name);
      emitDeclaration(node);
    }
  }

  ts.forEachChild(node, processNode);
}

// Add Plugin interface and PluginInfo first (from comments in original file)
output.push(`
// ============================================================================
// Plugin Interface
// ============================================================================

/**
 * Plugin metadata returned by the init function
 */
export interface PluginInfo {
  /** Name of the plugin */
  name: string;
  /** Version string (e.g., "1.0.0") */
  version: string;
  /** Optional author information */
  author?: string;
  /** Optional description of plugin functionality */
  description?: string;
}

/**
 * Plugin interface that all plugins must implement
 */
export interface Plugin {
  /**
   * Initialize the plugin with access to the Plugin API
   * @param api - The Plugin API instance
   * @returns Promise resolving to plugin metadata
   */
  init(api: PluginApi): Promise<PluginInfo>;

  /**
   * Optional cleanup function called when plugin is unloaded
   */
  destroy?(): Promise<void> | void;
}
`);

// Map renderer settings (MapRenderer.Settings, used by map overlays). The
// renderer's Settings.d.ts is self-contained, so it is copied verbatim into a
// namespace instead of making plugin-types depend on mudlet-map-renderer.
const rendererSettingsPath = path.join(
  PROJECT_ROOT, 'node_modules', 'mudlet-map-renderer', 'dist', 'types', 'Settings.d.ts'
);
const rendererSettings = fs.readFileSync(rendererSettingsPath, 'utf-8');
if (/^import /m.test(rendererSettings)) {
  console.error('❌ mudlet-map-renderer Settings.d.ts now has imports - update the MapRenderer namespace inlining');
  process.exit(1);
}
const rendererSettingsBody = rendererSettings
  // Runtime functions have no place in a types-only namespace
  .replace(/^export declare function[^\n]*\n?/gm, '')
  .replace(/^\/\/# sourceMappingURL=.*$/gm, '')
  .trimEnd()
  .split('\n')
  .map((line) => (line ? '  ' + line : line))
  .join('\n');
output.push(`
// ============================================================================
// Map Renderer Types (copied from mudlet-map-renderer)
// ============================================================================

export declare namespace MapRenderer {
${rendererSettingsBody}
}
`);

// We need to manually add types from dependencies that are referenced
// Add FormatState types
output.push(`
// ============================================================================
// Color Types
// ============================================================================

/**
 * Indexed color (0-255)
 */
export interface IndexedColor {
  space: "indexed";
  index: number;
}

/**
 * RGB color
 */
export interface RgbColor {
  space: "rgb";
  r: number;
  g: number;
  b: number;
}

/**
 * Hexadecimal color
 */
export interface HexColor {
  space: "hex";
  color: string;
}

/**
 * Union type for all color formats
 */
export type FormatColor = IndexedColor | RgbColor | HexColor;

/**
 * Hyperlink with callbacks
 */
export interface FormatHyperlink {
  onClick?: (ev: MouseEvent) => void;
  onContextMenu?: (ev: MouseEvent) => void;
  title?: string;
}

/**
 * Complete formatting state for text
 */
export interface FormatStateSnapshot {
  foreground?: FormatColor;
  background?: FormatColor;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  inverse?: boolean;
  strikethrough?: boolean;
  slowBlink?: boolean;
  rapidBlink?: boolean;
  hyperlink?: FormatHyperlink;
}


/**
 * Text range [start, end] for applying formatting
 */
export type TextRange = [start: number, end: number];

/**
 * Buffer segment with text and optional formatting state
 */
export interface BufferSegment {
  text: string;
  state?: FormatStateSnapshot;
}

// ============================================================================
// AnsiAwareBuffer - Line Manipulation
// ============================================================================

/**
 * Buffer for text with ANSI formatting
 * Represents a line of text with color and style information
 */
export declare class AnsiAwareBuffer {
  /**
   * Create a new AnsiAwareBuffer
   * @param initial - Initial text with ANSI codes, array of segments, or undefined
   * @param state - Optional default formatting state
   *
   * @example
   * // Create empty buffer
   * const buffer = new AnsiAwareBuffer();
   *
   * // Create from plain text
   * const buffer = new AnsiAwareBuffer("Hello world");
   *
   * // Create from text with default formatting
   * const buffer = new AnsiAwareBuffer("Hello", api.colors.fromHex('#ff0000'));
   *
   * // Create from ANSI string
   * const buffer = new AnsiAwareBuffer("\\x1b[31mRed text\\x1b[0m");
   *
   * // Create from segments
   * const segments: BufferSegment[] = [
   *   { text: "Hello ", state: api.colors.fromHex('#00ff00') },
   *   { text: "world", state: api.colors.fromHex('#0000ff') }
   * ];
   * const buffer = new AnsiAwareBuffer(segments);
   */
  constructor(initial?: string | BufferSegment[], state?: FormatStateSnapshot);
  /**
   * Get the plain text content without formatting
   */
  readonly text: string;

  /**
   * Get the total character length
   */
  readonly length: number;

  /**
   * Create a deep copy of this buffer
   */
  clone(): AnsiAwareBuffer;

  /**
   * Clear all content from the buffer
   */
  clear(): this;

  /**
   * Replace text in a range
   * @param range - [start, end] indices
   * @param text - New text to insert
   * @param state - Optional formatting to apply
   */
  replace(range: TextRange, text: string, state?: FormatStateSnapshot): this;

  /**
   * Insert text at an index
   * @param index - Position to insert at
   * @param text - Text to insert
   * @param state - Optional formatting to apply
   */
  insert(index: number, text: string, state?: FormatStateSnapshot): this;

  /**
   * Insert another buffer at an index
   * @param index - Position to insert at
   * @param buffer - Buffer to insert
   */
  insertBuffer(index: number, buffer: AnsiAwareBuffer): this;

  /**
   * Append another buffer to the end
   * @param buffer - Buffer to append
   */
  appendBuffer(buffer: AnsiAwareBuffer): this;

  /**
   * Prepend another buffer to the beginning
   * @param buffer - Buffer to prepend
   */
  prependBuffer(buffer: AnsiAwareBuffer): this;

  /**
   * Add text to the beginning of the line
   * @param text - Text to prepend
   * @param state - Optional formatting to apply
   */
  prepend(text: string, state?: FormatStateSnapshot): this;

  /**
   * Add text to the end of the line
   * @param text - Text to append
   * @param state - Optional formatting to apply
   */
  append(text: string, state?: FormatStateSnapshot): this;

  /**
   * Apply color/formatting to a text range
   * @param range - [start, end] indices
   * @param color - Color index (0-255) or full FormatStateSnapshot
   */
  color(range: TextRange, color: number | FormatStateSnapshot): this;

  /**
   * Apply color/formatting to specific words throughout the buffer
   * @param words - Single word or array of words to colorize
   * @param color - Color index (0-255) or full FormatStateSnapshot
   * @param options - Search options (caseInsensitive)
   *
   * @example
   * \`\`\`typescript
   * // Color a single word
   * line.colorWords("gold", api.colors.fromHex('#ffd700'));
   *
   * // Color multiple words
   * line.colorWords(["red", "blue"], 196, { caseInsensitive: true });
   * \`\`\`
   */
  colorWords(
    words: string | string[],
    color: number | FormatStateSnapshot,
    options?: { caseInsensitive?: boolean }
  ): this;

  /**
   * Make a text range clickable with event handlers
   * @param range - [start, end] indices
   * @param options - Link options (onClick, onContextMenu, title)
   *
   * @example
   * \`\`\`typescript
   * const text = "Click here";
   * const start = line.text.indexOf(text);
   * line.createLink([start, start + text.length], {
   *   onClick: () => api.output.print("Clicked!", "system"),
   *   title: "Click to execute"
   * });
   * \`\`\`
   */
  createLink(
    range: TextRange,
    options: {
      onClick?: (ev: MouseEvent) => void;
      onContextMenu?: (ev: MouseEvent) => void;
      title?: string;
    }
  ): this;

  /**
   * Make all occurrences of a text string clickable
   * @param text - Text to make clickable
   * @param options - Link options (onClick, onContextMenu, title)
   * @param searchOptions - Search options (caseInsensitive)
   *
   * @example
   * \`\`\`typescript
   * line.createLinksForText("potion", {
   *   onClick: () => api.output.print("Use potion", "system"),
   *   title: "Click to use"
   * }, { caseInsensitive: true });
   * \`\`\`
   */
  createLinksForText(
    text: string,
    options: {
      onClick?: (ev: MouseEvent) => void;
      onContextMenu?: (ev: MouseEvent) => void;
      title?: string;
    },
    searchOptions?: { caseInsensitive?: boolean }
  ): this;

  /**
   * Remove text in a range
   * @param range - [start, end] indices
   */
  remove(range: TextRange): this;
  
  /**
     * Returns the format state at the given character index.
     * This includes color information (foreground, background) and other formatting attributes.
     * Returns undefined if the character at that index has no formatting.
     */
    getStateAt(index: number): FormatStateSnapshot | undefined;
}

// ============================================================================
// Trigger System
// ============================================================================

/**
 * Callback function for triggers
 * @param line - The line buffer to potentially modify
 * @param matches - Regex match results
 * @param type - Line type (e.g., "prompt", "info", "error")
 * @returns Modified line or null to suppress the line
 */
export type TriggerCallback = (
  line: AnsiAwareBuffer,
  matches: RegExpMatchArray,
  type: string
) => AnsiAwareBuffer | null;

/**
 * Custom match function for advanced trigger patterns
 */
export type TriggerMatchFunction = (
  line: AnsiAwareBuffer,
  matches: RegExpMatchArray,
  type: string
) => RegExpMatchArray | undefined;

/**
 * Trigger pattern types
 */
export type TriggerSubPattern = string | RegExp | TriggerMatchFunction;
export type TriggerPattern = TriggerSubPattern | TriggerSubPattern[];

/**
 * Options for trigger behavior
 */
export interface TriggerOptions {
  /** Number of lines to keep child triggers active after parent matches */
  stayOpenLines?: number;
  /** Make regex case-insensitive */
  caseInsensitive?: boolean;
}

/**
 * Trigger instance
 */
export interface Trigger {
  /** Unique trigger ID */
  readonly id: string;

  /**
   * Register a child trigger (active after parent matches)
   * @param pattern - Pattern(s) to match
   * @param callback - Function to call on match
   * @param tag - Optional tag for grouping/removal
   * @param options - Trigger options
   */
  registerChild(
    pattern: TriggerPattern,
    callback?: TriggerCallback,
    tag?: string,
    options?: TriggerOptions
  ): Trigger;

  /**
   * Register a one-time child trigger (auto-removed after first match)
   * @param pattern - Pattern(s) to match
   * @param callback - Function to call on match
   * @param tag - Optional tag for grouping/removal
   * @param options - Trigger options
   */
  registerOneTimeChild(
    pattern: TriggerPattern,
    callback: TriggerCallback,
    tag?: string,
    options?: TriggerOptions
  ): Trigger;
}

/**
 * Helper function to match on line type
 * @param type - Line type to match (e.g., "prompt", "info")
 */
export function isType(type: string): TriggerMatchFunction;

// ============================================================================
// Map Position
// ============================================================================

/**
 * Map direction type
 */
export type MapDirection =
  | "north"
  | "south"
  | "east"
  | "west"
  | "northwest"
  | "northeast"
  | "southeast"
  | "southwest"
  | "up"
  | "down"
  | "in"
  | "out";

/**
 * Map room information
 */
export interface Room {
  /** Room ID */
  id: number;
  /** Area ID (numeric) */
  area: number;
  /** X coordinate */
  x: number;
  /** Y coordinate */
  y: number;
  /** Z coordinate (level) */
  z: number;
  /** Area identifier string */
  areaId: string;
  /** Room name */
  name: string;
  /** Room weight for pathfinding */
  weight: number;
  /** Room symbol */
  symbol: string;
  /** User-defined data */
  userData: Record<string, string>;
  /** Custom lines */
  customLines: Record<string, any>;
  /** Stub exits */
  stubs: number[];
  /** Room hash */
  hash: string;
  /** Environment ID */
  env: number;
  /** Exit connections to room IDs */
  exits: Record<MapDirection, number>;
  /** Door types (1=open, 2=closed, 3=locked) */
  doors: Record<MapDirection, 1 | 2 | 3>;
  /** Special exits with custom commands */
  specialExits: Record<string, number>;
}

// ============================================================================
// Object List Filter Types
// ============================================================================

/**
 * Object data from GMCP
 */
export interface ObjectData {
  num: number;
  id?: string;
  desc?: string;
  hp?: number;
  maxhp?: number;
  image?: string;
  attackers?: { num: number; id?: string }[];
}

/**
 * Entry context provided to filters
 */
export interface EntryContext {
  /** The object data from GMCP */
  object: ObjectData;
  /** The display number/shortcut for this entry */
  displayNum: number;
  /** Whether this is the avatar's current target */
  isTarget: boolean;
  /** Whether this is the avatar's next target in queue */
  isNextTarget: boolean;
  /** Whether this object is a team member */
  isTeammate: boolean;
  /** The raw description text */
  rawDescription: string;
  /** Whether this object is currently attacking */
  isAttacking: boolean;
  /** Current attack command being used */
  attackCommand: string;
}

/**
 * Entry style modifications
 */
export interface EntryStyle {
  /** Color for the description text (CSS color value) */
  descriptionColor?: string;
  /** Whether to apply italic style to description */
  italic?: boolean;
  /** Color for the HP bar (CSS color value) */
  hpBarColor?: string;
  /** Additional CSS class names to add to the entry */
  cssClasses?: string[];
  /** Custom prefix to add before the entry (e.g., icons, indicators) */
  prefix?: string;
  /** Custom suffix to add after the entry */
  suffix?: string;
}

/**
 * Entry content modifications
 */
export interface EntryContent {
  /** Modified description text (replaces original if provided) */
  description?: string;
  /** Modified HP display (replaces original if provided) */
  hpBar?: string;
  /** Modified number label (replaces original if provided) */
  numberLabel?: string;
}

/**
 * Filter result - mutate this object to modify the entry
 */
export interface FilterResult {
  /** Style modifications - mutate this object to add/change styles */
  style: EntryStyle;
  /** Content modifications - mutate this object to replace content */
  content: EntryContent;
  /** If true, prevents subsequent filters from running */
  stopPropagation?: boolean;
}

/**
 * Object list entry filter function
 *
 * Receives context about the entry and the current accumulated result from previous filters.
 * Filters modify the result object directly and optionally return { stopPropagation: true }.
 *
 * @param context - Information about the object being rendered
 * @param result - Current accumulated style and content (mutate this object)
 * @returns void or { stopPropagation: true } to prevent further filters
 *
 * @example
 * \`\`\`typescript
 * const highlightDragons: ObjectListEntryFilter = (context, result) => {
 *   if (context.rawDescription.toLowerCase().includes("smok")) {
 *     result.style.descriptionColor = "#ff0000";
 *     result.style.prefix = (result.style.prefix || "") + "🐉 ";
 *   }
 * };
 *
 * api.objectListFilters.register("dragons", highlightDragons, 10);
 * \`\`\`
 */
export type ObjectListEntryFilter = (
  context: EntryContext,
  result: FilterResult
) => void | { stopPropagation: true };

// ============================================================================
// Live Map Edit Types
// ============================================================================

/**
 * A single room's worth of live map edits, as accepted by \`api.map.applyChanges\`.
 * Only the fields present are touched; everything else on the room is left alone.
 */
export interface RoomChange {
  /** Room to patch. Ignored if the map has no such room. */
  roomId: number;
  /**
   * What to do with the room:
   * - \`patch\` (default) — update an existing room, skip if it is missing.
   * - \`upsert\` — update, or create it when missing. Needs \`area\`.
   * - \`delete\` — remove the room from the map entirely.
   */
  op?: 'patch' | 'upsert' | 'delete';
  /** Area to place a newly created room in. Only read when upserting. */
  area?: number;
  /** Room name. */
  name?: string;
  /** Symbol drawn in the room square (Mudlet's roomChar). */
  roomChar?: string;
  /** Environment/colour id. */
  env?: number;
  /** Pathfinding weight. */
  weight?: number;
  /** Map coordinates. Moving a room needs the area geometry rebuild. */
  x?: number;
  y?: number;
  z?: number;
  /** Replaces the room's exits wholesale. */
  exits?: Partial<Record<MapDirection, number>>;
  /** Replaces the room's special exits wholesale. */
  specialExits?: Record<string, number>;
  /** Merged into existing userData; a \`null\` value removes that key. */
  userData?: Record<string, string | null>;
}

/**
 * The whole map, as published in \`mapExport.json\`: an array of areas with
 * coordinates in source orientation. Accepted by \`api.map.replaceMap\`.
 */
export type MapExportData = MapAreaData[];

/**
 * One area in the shape the renderer consumes — the same objects found in the
 * published \`mapExport.json\`. Coordinates are in source orientation (y-up, as
 * Mudlet stores them); \`api.map.syncAreas\` flips y on the way in, exactly as the
 * map does when it first loads.
 */
export interface MapAreaData {
  areaId: string | number;
  areaName?: string;
  rooms: MapData.Room[];
  labels?: unknown[];
}

/**
 * Tuning for \`api.map.applyChanges\`. Every rebuild defaults to \`true\`, which is
 * always correct but heavier than a cosmetic edit needs.
 */
export interface ApplyChangesOptions {
  /**
   * Rebuild renderer geometry for affected areas. Required for anything that
   * changes what is drawn (symbols, colours, exits). Default \`true\`.
   */
  rebuildAreas?: boolean;
  /**
   * Rebuild the pathfinder. Only exits and weights affect routing, so a pure
   * name/symbol change can skip it. Default \`true\`.
   */
  rebuildPaths?: boolean;
  /** Redraw the current view when done. Default \`true\`. */
  rerender?: boolean;
}

// ============================================================================
// Enemy Bind Resolver Types
// ============================================================================

/**
 * A single enemy candidate eligible for a bind slot (F1/F2/F3)
 */
export interface EnemyBindCandidate {
  /** Object number (matches the GMCP object id; bind with \`ob_<num>\`) */
  num: number;
  /** Object description/name as shown in the bind line */
  desc: string;
}

/**
 * Read-only view of an object on the current location, passed to resolvers
 */
export interface EnemyBindLocationObject {
  num: number;
  desc?: string;
  hp?: number;
  attack_num?: boolean | number;
  shortcut?: string;
  __category?: "player" | "team" | "rest" | "rest-noncombat";
}

/**
 * Enemy bind resolver function
 *
 * Receives the current (ordered) candidate list and every object on the location,
 * and returns the candidate list to use going forward. Return a reordered and/or
 * extended array to change which enemies get bound, or nothing to leave it unchanged.
 *
 * Resolvers compose: the output of one becomes the \`candidates\` input of the next,
 * in priority order (higher priority runs first).
 *
 * @param candidates - Current ordered candidate list (output of previous resolvers)
 * @param allObjects - Every object on the current location
 */
export type EnemyBindResolver = (
  candidates: EnemyBindCandidate[],
  allObjects: EnemyBindLocationObject[]
) => EnemyBindCandidate[] | void;
`);

// Now we need to add the ClientEvents interface
// Read the events file to get the event types
const eventsFilePath = path.join(PROJECT_ROOT, 'src', 'shared', 'events', 'clientEvents.ts');
if (fs.existsSync(eventsFilePath)) {
  const eventsContent = fs.readFileSync(eventsFilePath, 'utf-8');

  output.push(`
// ============================================================================
// Event Types
// ============================================================================

/**
 * Send command event payload
 */
export interface SendCommandEvent {
  command: string;
  echo?: boolean;
  options?: {
    mode?: string;
    [key: string]: any;
  };
}

/**
 * Notification event payload
 */
export interface NotificationPayload {
  text: string;
  time?: number;
}

/**
 * Storage event payload
 */
export interface StorageEventPayload {
  key: string;
  value: unknown;
}

/**
 * Multibind list event payload
 */
export interface MultibindList {
  list: {
    index: number;
    action: string;
    /** Key label, e.g. "ALT+1". */
    label: string;
    /** Display name of a temporary bind - shown instead of the action when set. */
    name?: string;
    /** Slot filled by a temporary (plugin) bind rather than a saved one. */
    temporary?: boolean;
    /** Slot a temporary bind asked to highlight. */
    highlight?: boolean;
  }[];
}

/**
 * Message event payload (output text)
 */
export type MessageEventPayload = [text: string | AnsiAwareBuffer, type?: string, timestamp?: number];

/**
 * Recording auto-stop event payload
 */
export type RecordingAutoStopPayload = [name: string | null, save?: boolean];

/**
 * Playback index event payload
 */
export type PlaybackIndexPayload = [current: number, total: number];

/**
 * Knowledge report action
 */
export type KnowledgeReportAction =
  | { type: "completeLibrary"; libraryId: string }
  | { type: "resetLibrary"; libraryId: string };

/**
 * Package status event payload
 */
export interface PackageStatus {
  recipient: string;
  seconds?: number;
}

/**
 * Plugin loaded event payload
 */
export interface PluginLoadedPayload {
  url: string;
  info: {
    name: string;
    version: string;
    author?: string;
    description?: string;
  };
}

/**
 * Plugin error event payload
 */
export interface PluginErrorPayload {
  url: string;
  error: string;
}

/**
 * Plugin destroyed event payload
 */
export interface PluginDestroyedPayload {
  url: string;
}

/**
 * Clock update event payload
 */
export interface ClockUpdatePayload {
  domain: "Empire" | "Ishtar";
  hours: number;
  minutes: number;
  precision: number;
  sunrise: number | string | "?";
  sunset: number | string | "?";
  dayLabel: string;
  dayOfMonth: number;
  dayOfYear: number;
  daylight?: boolean;
  season?: number;
}

/**
 * Clock domain active event payload
 */
export interface ClockDomainActivePayload {
  domain: "Empire" | "Ishtar";
}

/**
 * Clock mismatch event payload
 */
export interface ClockMismatchPayload {
  domain: "Empire" | "Ishtar";
  type: "sunrise" | "sunset";
  dayOfYear: number;
  expectedHour: number;
  observedHour: number;
  observedMinutes: number;
  indicatedHour?: string;
}

/**
 * Clock sun event payload (sunrise/sunset)
 */
export interface ClockSunEventPayload {
  domain: "Empire" | "Ishtar";
  dayOfYear: number;
  observedHour: number;
  observedMinutes: number;
  indicatedHour?: string;
}

/**
 * Known client events with their payloads
 * Subscribe to these events using api.events.on()
 */
export interface ClientEvents {
  /** Command sent to the MUD server */
  "command": string;
  /** Port connection established */
  "port-connected": void;
  /** Output line sent to display */
  "output-sent": number;
  /** Buffer sent */
  "buffer-sent": number;
  /** Map position changed */
  "mapMove": void;
  /** Map data loaded and ready (fired once, after initial map initialization) */
  "mapReady": void;
  /** Step back in location history */
  "stepBack": void;
  /** Lead to specific room ID */
  "leadTo": number;
  /** Clear lead to destination */
  "clearLeadTo": void;
  /** Map path data emitted when destination(s) change. null when no active path. */
  "mapPath": { segments: Array<{ path: number[]; color: string }> } | null;
  /** Display notification */
  "notify": NotificationPayload;
  /** Lamp timer updated */
  "lampTimer": number | null;
  /** Cover timer updated */
  "coverTimer": number | null;
  /** Break item warning */
  "breakItem": { text: string; command?: string } | null;
  /** Package delivery status */
  "packageStatus": PackageStatus | null;
  /** Release guard status */
  "releaseGuard": boolean;
  /** Attack mode changed */
  "attackMode": "A" | "AW" | "AWR";
  /** Content width changed */
  "contentWidth": number;
  /** Entered a location. direction is the direction that led to this location (null when set via other means than move) */
  "enterLocation": { id: number; room: unknown; direction: string | null };
  /** Highlights updated */
  "highlights": [number[]];
  /** Multibind list updated */
  "multibinds": MultibindList;
  /** Letter composer state */
  "letterComposer": { open: boolean };
  /** Letter composer submit */
  "letterComposer.submit": unknown;
  /** Letter composer preview */
  "letterComposer.preview": unknown;
  /** NPC information */
  "npc": unknown;
  /** Zask timer status */
  "zaskTimer": { seconds: number; ok: boolean } | null;
  /** Move mode changed */
  "moveModeChanged": number;
  /** Ping measurement */
  "ping": number | null;
  /** Transport timer status */
  "transportTimer": unknown;
  /** Combat timer */
  "combatTimer": number | null;
  /** Team leader target without avatar */
  "teamLeaderTargetNoAvatar": number;
  /** Team leader target with avatar */
  "teamLeaderTargetAvatar": void;
  /** Team composition changed */
  "teamChange": void;
  /** Is team leader status */
  "isTeamLeader": boolean;
  /** Reset client state */
  "reset": void;
  /** Refresh map position when able */
  "refreshPositionWhenAble": void;
  /** Knowledge report */
  "knowledgeReport": unknown | null;
  /** Open knowledge report popup */
  "knowledgeReport.popup.open": void;
  /** Knowledge details report */
  "knowledgeDetailsReport": unknown | null;
  /** Open knowledge details popup */
  "knowledgeDetails.popup.open": void;
  /** Knowledge report action */
  "knowledgeReportAction": KnowledgeReportAction;
  /** Send command to server */
  "sendCommand": SendCommandEvent;
  /** Request herb counts */
  "requestHerbCounts": void;
  /** Herb manager closed */
  "herbManagerClose": void;
  /** Herb counts data */
  "herbCounts": unknown;
  /** Herb manager opened */
  "herbManagerOpen": void;
  /** Play sound effect */
  "sound:play": { key: string };
  /** Play beep sound */
  "playBeep": void;
  /** Line start marker */
  "line-start": void;
  /** Storage value changed */
  "storage": StorageEventPayload;
  /** Settings updated */
  "settings": unknown;
  /** Binds updated */
  "binds": unknown;
  /** UI settings updated */
  "uiSettings": unknown;
  /** Mobile buttons settings updated */
  "mobileButtonsSettings": unknown;
  /** Pauser started */
  "pauserStart": void;
  /** Pauser ended */
  "pauserEnd": void;
  /** Client connected to server */
  "client.connect": void;
  /** Client disconnected from server */
  "client.disconnect": void;
  /** WebSocket opened */
  "open": Event;
  /** WebSocket closed */
  "close": CloseEvent;
  /** Error occurred */
  "error": unknown;
  /** GMCP data received */
  "gmcp": { path: string; value: unknown };
  /** Recording started */
  "recording.start": string;
  /** Recording stopped */
  "recording.stop": boolean | undefined;
  /** Auto-recording started */
  "recording.auto.start": string | null | undefined;
  /** Auto-recording stopped */
  "recording.auto.stop": RecordingAutoStopPayload;
  /** Playback stopped */
  "playback.stop": void;
  /** Playback paused */
  "playback.pause": void;
  /** Playback resumed */
  "playback.resume": void;
  /** Playback started */
  "playback.start": number | undefined;
  /** Playback speed changed */
  "playback.speed": number;
  /** Playback index changed */
  "playback.index": PlaybackIndexPayload;
  /** Message output */
  "message": MessageEventPayload;
  /** Attack queue changed */
  "attackQueueChange": string[];
  /** Clear attack queue */
  "clearAttackQueue": void;
  /** Add to attack queue */
  "addToAttackQueue": string;
  /** Remove from attack queue */
  "removeFromAttackQueue": string;
  /** Objects parsed */
  "parsedObjects": void;
  /** Numbers parsed */
  "parsedNums": { nums: number[] };
  /** Kill event */
  "kill": { killer: "ME" | "TEAM" | "OTHER" };
  /** Enemy killed */
  "enemyKilled": { objNum: number; killer: "ME" | "TEAM" | "OTHER"; hasBody?: boolean };
  /** All enemies killed */
  "allEnemiesKilled": void;
  /** Plugin loaded successfully */
  "plugin:loaded": PluginLoadedPayload;
  /** Plugin error occurred */
  "plugin:error": PluginErrorPayload;
  /** Plugin destroyed */
  "plugin:destroyed": PluginDestroyedPayload;
  /** Clock update */
  "clock.update": ClockUpdatePayload;
  /** Clock domain active */
  "clock.domain.active": ClockDomainActivePayload;
  /** Clock popup opened */
  "clock.popup.open": { domain?: "Empire" | "Ishtar" };
  /** Clock mismatch detected */
  "clock.mismatch": ClockMismatchPayload;
  /** Clock sunrise */
  "clock.sunrise": ClockSunEventPayload;
  /** Clock sunset */
  "clock.sunset": ClockSunEventPayload;
  /** Can wield weapon after knockoff */
  "canWieldAfterKnockOff": void;
  /** Team leader performed special exit follow */
  "followSpecialExit": { exit: string };
  /** GMCP events with dynamic paths (e.g., gmcp.room.info, gmcp.char.vitals) */
  [key: \`gmcp.\${string}\`]: unknown;
  /** GMCP message events */
  [key: \`gmcp_msg.\${string}\`]: AnsiAwareBuffer;
}
`);
}

output.push(`
// ============================================================================
// API Namespaces
// ============================================================================
`);

// Process source file for API interfaces
processNode(sourceFile);

// ============================================================================
// Supporting types
// ============================================================================
// Public signatures reference types declared outside PluginApi.ts (settings,
// macro contexts, people entries, ...). Follow every type reference in the
// emitted declarations and inline what it points at, transitively, so the
// generated file is self-contained.

// react types are imported rather than inlined; plugins using React
// footers/popups already depend on @types/react.
const EXTERNAL_IMPORTS = {
  react: (name) => (name === 'React'
    ? 'import type * as React from "react";'
    : `import type { ${name} } from "react";`),
};

// Ambient namespaces that are not imported (so the checker cannot resolve them
// from PluginApi.ts alone); inlined verbatim like MapRenderer above.
const AMBIENT_NAMESPACES = {
  MapData: path.join(PROJECT_ROOT, 'src', 'client', 'types', 'MapData.d.ts'),
};

const declaredNames = new Set(exportedTypes);
for (const match of output.join('\n').matchAll(
  /^export (?:declare )?(?:interface|type|class|namespace|function) (\w+)/gm
)) {
  declaredNames.add(match[1]);
}

const externalImports = new Set();
let supportingHeaderAdded = false;
function pushSupportingHeader() {
  if (supportingHeaderAdded) return;
  supportingHeaderAdded = true;
  output.push(`
// ============================================================================
// Supporting Types (inlined from the modules PluginApi.ts depends on)
// ============================================================================
`);
}

function leftmostIdentifier(name) {
  while (ts.isQualifiedName(name)) name = name.left;
  while (ts.isPropertyAccessExpression(name)) name = name.expression;
  return ts.isIdentifier(name) ? name : null;
}

function packageOf(fileName) {
  const match = fileName.replace(/\\/g, '/').match(/\/node_modules\/(?:@types\/)?((?:@[^/]+\/)?[^/]+)\//);
  return match ? match[1] : null;
}

function resolveReference(identifier) {
  const name = identifier.text;
  if (declaredNames.has(name)) return;

  let symbol = checker.getSymbolAtLocation(identifier);
  if (symbol && symbol.flags & ts.SymbolFlags.TypeParameter) return;
  if (symbol && symbol.flags & ts.SymbolFlags.Alias) symbol = checker.getAliasedSymbol(symbol);

  const declarations = symbol?.declarations ?? [];
  if (declarations.length === 0) {
    if (AMBIENT_NAMESPACES[name]) {
      const body = fs.readFileSync(AMBIENT_NAMESPACES[name], 'utf-8')
        .trim()
        .replace(/^declare namespace/, 'export declare namespace');
      pushSupportingHeader();
      output.push('\n' + body);
      declaredNames.add(name);
      return;
    }
    console.error(`❌ Cannot resolve type '${name}' referenced by the plugin API`);
    process.exit(1);
  }
  const declFile = declarations[0].getSourceFile();

  // Built-in lib types (Record, Promise, HTMLElement, ...)
  if (program.isSourceFileDefaultLibrary(declFile)) return;

  const pkg = packageOf(declFile.fileName);
  if (pkg) {
    const makeImport = EXTERNAL_IMPORTS[pkg];
    if (!makeImport) {
      console.error(`❌ Type '${name}' comes from '${pkg}' - add it to EXTERNAL_IMPORTS or inline it`);
      process.exit(1);
    }
    externalImports.add(makeImport(name));
    declaredNames.add(name);
    return;
  }

  declaredNames.add(name);
  pushSupportingHeader();
  for (const decl of declarations) {
    const declName = decl.name?.text;
    if (ts.isClassDeclaration(decl)) {
      // Runtime classes (e.g. Client) are not part of the stable API surface;
      // expose them opaquely instead of dragging in their whole implementation.
      output.push(`\n/** Internal ${name} instance (not part of the stable plugin API) */\nexport type ${name} = any;`);
      return;
    }
    if (declName !== name) {
      console.error(`❌ Type '${name}' is imported under another name ('${declName}') - not supported`);
      process.exit(1);
    }
    if (ts.isInterfaceDeclaration(decl) || ts.isTypeAliasDeclaration(decl)) {
      emitDeclaration(decl, decl.getSourceFile());
    } else if (ts.isEnumDeclaration(decl)) {
      emitDeclaration(decl, decl.getSourceFile());
      output[output.length - 1] = output[output.length - 1].replace(/^\nexport /, '\nexport declare ');
    } else {
      console.error(`❌ Don't know how to inline '${name}' (${ts.SyntaxKind[decl.kind]})`);
      process.exit(1);
    }
  }
}

function collectReferences(node) {
  let identifier = null;
  if (ts.isTypeReferenceNode(node)) identifier = leftmostIdentifier(node.typeName);
  else if (ts.isExpressionWithTypeArguments(node)) identifier = leftmostIdentifier(node.expression);
  else if (ts.isTypeQueryNode(node)) identifier = leftmostIdentifier(node.exprName);
  if (identifier) resolveReference(identifier);
  ts.forEachChild(node, collectReferences);
}

for (let i = 0; i < emittedNodes.length; i++) {
  collectReferences(emittedNodes[i]);
}

if (externalImports.size > 0) {
  output.splice(1, 0, [...externalImports].sort().join('\n') + '\n');
}

// Add final exports
output.push(`
// ============================================================================
// Exports
// ============================================================================

export default PluginApi;
`);

// Write output file
const finalOutput = output.join('\n');
fs.writeFileSync(OUTPUT_FILE, finalOutput, 'utf-8');

console.log('✅ Type definitions generated successfully!');
console.log(`📦 Exported ${exportedTypes.size} type definitions`);
console.log(`📏 Output size: ${(finalOutput.length / 1024).toFixed(2)} KB`);
