/**
 * Generate plugin-types/index.d.ts from src/client/PluginApi.ts
 *
 * This script extracts type definitions from the source code and generates
 * a standalone .d.ts file for external plugin developers.
 */

const ts = require('typescript');
const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const SOURCE_FILE = path.join(PROJECT_ROOT, 'src', 'client', 'PluginApi.ts');
const OUTPUT_FILE = path.join(__dirname, 'index.d.ts');
const TSCONFIG_PATH = path.join(PROJECT_ROOT, 'tsconfig.json');

console.log('🔧 Generating plugin types from source...');
console.log(`📄 Source: ${path.relative(PROJECT_ROOT, SOURCE_FILE)}`);
console.log(`📝 Output: ${path.relative(PROJECT_ROOT, OUTPUT_FILE)}`);

// Read tsconfig
const configFile = ts.readConfigFile(TSCONFIG_PATH, ts.sys.readFile);
const parsedConfig = ts.parseJsonConfigFileContent(
  configFile.config,
  ts.sys,
  PROJECT_ROOT
);

// Create program
const program = ts.createProgram({
  rootNames: [SOURCE_FILE],
  options: {
    ...parsedConfig.options,
    declaration: true,
    emitDeclarationOnly: true,
    declarationDir: path.join(__dirname, '.temp'),
    noEmit: false
  }
});

const sourceFile = program.getSourceFile(SOURCE_FILE);
if (!sourceFile) {
  console.error('❌ Could not load source file');
  process.exit(1);
}

const checker = program.getTypeChecker();
const output = [];

// Header comment
output.push(`/**
 * TypeScript Type Definitions for Arkadia Web Client Plugins
 *
 * This package provides TypeScript type definitions for developing
 * plugins for the Arkadia Web Client.
 *
 * MAINTAINER NOTE: This file is AUTO-GENERATED from src/client/PluginApi.ts
 * Do not edit this file directly. Run 'yarn build:types' to regenerate.
 *
 * @packageDocumentation
 */
`);

// Track what we've already exported to avoid duplicates
const exportedTypes = new Set();

// Helper to get JSDoc comments
function getJsDocComments(node) {
  const fullText = node.getFullText();
  const jsDocRegex = /\/\*\*[\s\S]*?\*\//g;
  const matches = fullText.match(jsDocRegex);
  return matches ? matches[matches.length - 1] : null;
}

// Helper to check if a type should be exported
function shouldExport(node) {
  // Export interfaces and type aliases
  if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) {
    const name = node.name?.text;

    // Skip internal implementation details
    if (name?.includes('Impl') || name?.includes('Internal')) {
      return false;
    }

    // Export API-related types
    if (name?.endsWith('Api') ||
        name?.endsWith('Handle') ||
        name?.endsWith('Event') ||
        name?.endsWith('Payload') ||
        name?.endsWith('Options') ||
        name?.endsWith('Definition') ||
        name?.endsWith('State') ||
        name === 'PluginApi' ||
        name === 'PluginInfo' ||
        name === 'Plugin' ||
        name === 'PopupContent' ||
        name === 'TriggerCallback' ||
        name === 'TriggerMatchFunction' ||
        name === 'TriggerPattern' ||
        name === 'TriggerSubPattern' ||
        name === 'Trigger' ||
        name === 'LocationObject' ||
        name === 'EventKey' ||
        name === 'EventParams' ||
        name === 'EventListener' ||
        // Object list filter types
        name === 'ObjectListEntryFilter' ||
        name === 'EntryContext' ||
        name === 'FilterResult' ||
        name === 'EntryStyle' ||
        name === 'EntryContent' ||
        name === 'ObjectData' ||
        // Herb database types
        name === 'HerbsData' ||
        name === 'HerbForms' ||
        name === 'HerbUse' ||
        // Container types
        name === 'ContainerType' ||
        name === 'ContainerForms' ||
        // Magics data types
        name === 'MagicEntry' ||
        name === 'MagicsFile' ||
        name === 'MagicKeysData') {
      return true;
    }
  }

  return false;
}

// Helper to get JSDoc comments (only the leading JSDoc before the node)
function getLeadingJsDoc(node) {
  const fullText = node.getFullText(sourceFile);
  const nodeText = node.getText(sourceFile);
  const leading = fullText.substring(0, fullText.indexOf(nodeText));

  // Extract JSDoc comment (/** ... */)
  const jsDocMatch = leading.match(/\/\*\*[\s\S]*?\*\//);
  return jsDocMatch ? jsDocMatch[0] : null;
}

// Helper to convert node to string
function nodeToString(node) {
  const printer = ts.createPrinter({
    newLine: ts.NewLineKind.LineFeed,
    removeComments: false  // Keep comments for interface members
  });

  let result = printer.printNode(ts.EmitHint.Unspecified, node, sourceFile);

  // Remove leading JSDoc from the result (we'll add it separately to avoid export duplication)
  // This regex removes JSDoc comments that appear before the first non-comment token
  result = result.replace(/^(\s*)\/\*\*[\s\S]*?\*\/\s*/, '$1');

  // Remove 'export ' keyword if present (TypeScript printer adds it)
  result = result.replace(/^export\s+/, '');

  return result;
}

// Process the source file
function processNode(node) {
  if (shouldExport(node)) {
    const name = node.name?.text;
    if (name && !exportedTypes.has(name)) {
      exportedTypes.add(name);

      const jsDoc = getLeadingJsDoc(node);
      const declaration = nodeToString(node);

      if (jsDoc) {
        output.push('\n' + jsDoc);
      }
      output.push('\nexport ' + declaration);
    }
  }

  ts.forEachChild(node, processNode);
}

// Add Plugin interface and PluginInfo first (from comments in original file)
output.push(`
// ============================================================================
// Plugin Interface
// ============================================================================

/**
 * Plugin metadata returned by the init function
 */
export interface PluginInfo {
  /** Name of the plugin */
  name: string;
  /** Version string (e.g., "1.0.0") */
  version: string;
  /** Optional author information */
  author?: string;
  /** Optional description of plugin functionality */
  description?: string;
}

/**
 * Plugin interface that all plugins must implement
 */
export interface Plugin {
  /**
   * Initialize the plugin with access to the Plugin API
   * @param api - The Plugin API instance
   * @returns Promise resolving to plugin metadata
   */
  init(api: PluginApi): Promise<PluginInfo>;

  /**
   * Optional cleanup function called when plugin is unloaded
   */
  destroy?(): Promise<void> | void;
}
`);

// We need to manually add types from dependencies that are referenced
// Add FormatState types
output.push(`
// ============================================================================
// Color Types
// ============================================================================

/**
 * Indexed color (0-255)
 */
export interface IndexedColor {
  space: "indexed";
  index: number;
}

/**
 * RGB color
 */
export interface RgbColor {
  space: "rgb";
  r: number;
  g: number;
  b: number;
}

/**
 * Hexadecimal color
 */
export interface HexColor {
  space: "hex";
  color: string;
}

/**
 * Union type for all color formats
 */
export type FormatColor = IndexedColor | RgbColor | HexColor;

/**
 * Hyperlink with callbacks
 */
export interface FormatHyperlink {
  onClick?: (ev: MouseEvent) => void;
  onContextMenu?: (ev: MouseEvent) => void;
  title?: string;
}

/**
 * Complete formatting state for text
 */
export interface FormatStateSnapshot {
  foreground?: FormatColor;
  background?: FormatColor;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  inverse?: boolean;
  strikethrough?: boolean;
  slowBlink?: boolean;
  rapidBlink?: boolean;
  hyperlink?: FormatHyperlink;
}


/**
 * Text range [start, end] for applying formatting
 */
export type TextRange = [start: number, end: number];

/**
 * Buffer segment with text and optional formatting state
 */
export interface BufferSegment {
  text: string;
  state?: FormatStateSnapshot;
}

// ============================================================================
// AnsiAwareBuffer - Line Manipulation
// ============================================================================

/**
 * Buffer for text with ANSI formatting
 * Represents a line of text with color and style information
 */
export declare class AnsiAwareBuffer {
  /**
   * Create a new AnsiAwareBuffer
   * @param initial - Initial text with ANSI codes, array of segments, or undefined
   * @param state - Optional default formatting state
   *
   * @example
   * // Create empty buffer
   * const buffer = new AnsiAwareBuffer();
   *
   * // Create from plain text
   * const buffer = new AnsiAwareBuffer("Hello world");
   *
   * // Create from text with default formatting
   * const buffer = new AnsiAwareBuffer("Hello", api.colors.fromHex('#ff0000'));
   *
   * // Create from ANSI string
   * const buffer = new AnsiAwareBuffer("\\x1b[31mRed text\\x1b[0m");
   *
   * // Create from segments
   * const segments: BufferSegment[] = [
   *   { text: "Hello ", state: api.colors.fromHex('#00ff00') },
   *   { text: "world", state: api.colors.fromHex('#0000ff') }
   * ];
   * const buffer = new AnsiAwareBuffer(segments);
   */
  constructor(initial?: string | BufferSegment[], state?: FormatStateSnapshot);
  /**
   * Get the plain text content without formatting
   */
  readonly text: string;

  /**
   * Get the total character length
   */
  readonly length: number;

  /**
   * Create a deep copy of this buffer
   */
  clone(): AnsiAwareBuffer;

  /**
   * Clear all content from the buffer
   */
  clear(): this;

  /**
   * Replace text in a range
   * @param range - [start, end] indices
   * @param text - New text to insert
   * @param state - Optional formatting to apply
   */
  replace(range: TextRange, text: string, state?: FormatStateSnapshot): this;

  /**
   * Insert text at an index
   * @param index - Position to insert at
   * @param text - Text to insert
   * @param state - Optional formatting to apply
   */
  insert(index: number, text: string, state?: FormatStateSnapshot): this;

  /**
   * Insert another buffer at an index
   * @param index - Position to insert at
   * @param buffer - Buffer to insert
   */
  insertBuffer(index: number, buffer: AnsiAwareBuffer): this;

  /**
   * Append another buffer to the end
   * @param buffer - Buffer to append
   */
  appendBuffer(buffer: AnsiAwareBuffer): this;

  /**
   * Prepend another buffer to the beginning
   * @param buffer - Buffer to prepend
   */
  prependBuffer(buffer: AnsiAwareBuffer): this;

  /**
   * Add text to the beginning of the line
   * @param text - Text to prepend
   * @param state - Optional formatting to apply
   */
  prepend(text: string, state?: FormatStateSnapshot): this;

  /**
   * Add text to the end of the line
   * @param text - Text to append
   * @param state - Optional formatting to apply
   */
  append(text: string, state?: FormatStateSnapshot): this;

  /**
   * Apply color/formatting to a text range
   * @param range - [start, end] indices
   * @param color - Color index (0-255) or full FormatStateSnapshot
   */
  color(range: TextRange, color: number | FormatStateSnapshot): this;

  /**
   * Apply color/formatting to specific words throughout the buffer
   * @param words - Single word or array of words to colorize
   * @param color - Color index (0-255) or full FormatStateSnapshot
   * @param options - Search options (caseInsensitive)
   *
   * @example
   * \`\`\`typescript
   * // Color a single word
   * line.colorWords("gold", api.colors.fromHex('#ffd700'));
   *
   * // Color multiple words
   * line.colorWords(["red", "blue"], 196, { caseInsensitive: true });
   * \`\`\`
   */
  colorWords(
    words: string | string[],
    color: number | FormatStateSnapshot,
    options?: { caseInsensitive?: boolean }
  ): this;

  /**
   * Make a text range clickable with event handlers
   * @param range - [start, end] indices
   * @param options - Link options (onClick, onContextMenu, title)
   *
   * @example
   * \`\`\`typescript
   * const text = "Click here";
   * const start = line.text.indexOf(text);
   * line.createLink([start, start + text.length], {
   *   onClick: () => api.output.print("Clicked!", "system"),
   *   title: "Click to execute"
   * });
   * \`\`\`
   */
  createLink(
    range: TextRange,
    options: {
      onClick?: (ev: MouseEvent) => void;
      onContextMenu?: (ev: MouseEvent) => void;
      title?: string;
    }
  ): this;

  /**
   * Make all occurrences of a text string clickable
   * @param text - Text to make clickable
   * @param options - Link options (onClick, onContextMenu, title)
   * @param searchOptions - Search options (caseInsensitive)
   *
   * @example
   * \`\`\`typescript
   * line.createLinksForText("potion", {
   *   onClick: () => api.output.print("Use potion", "system"),
   *   title: "Click to use"
   * }, { caseInsensitive: true });
   * \`\`\`
   */
  createLinksForText(
    text: string,
    options: {
      onClick?: (ev: MouseEvent) => void;
      onContextMenu?: (ev: MouseEvent) => void;
      title?: string;
    },
    searchOptions?: { caseInsensitive?: boolean }
  ): this;

  /**
   * Remove text in a range
   * @param range - [start, end] indices
   */
  remove(range: TextRange): this;
  
  /**
     * Returns the format state at the given character index.
     * This includes color information (foreground, background) and other formatting attributes.
     * Returns undefined if the character at that index has no formatting.
     */
    getStateAt(index: number): FormatStateSnapshot | undefined;
}

// ============================================================================
// Trigger System
// ============================================================================

/**
 * Callback function for triggers
 * @param line - The line buffer to potentially modify
 * @param matches - Regex match results
 * @param type - Line type (e.g., "prompt", "info", "error")
 * @returns Modified line or null to suppress the line
 */
export type TriggerCallback = (
  line: AnsiAwareBuffer,
  matches: RegExpMatchArray,
  type: string
) => AnsiAwareBuffer | null;

/**
 * Custom match function for advanced trigger patterns
 */
export type TriggerMatchFunction = (
  line: AnsiAwareBuffer,
  matches: RegExpMatchArray,
  type: string
) => RegExpMatchArray | undefined;

/**
 * Trigger pattern types
 */
export type TriggerSubPattern = string | RegExp | TriggerMatchFunction;
export type TriggerPattern = TriggerSubPattern | TriggerSubPattern[];

/**
 * Options for trigger behavior
 */
export interface TriggerOptions {
  /** Number of lines to keep child triggers active after parent matches */
  stayOpenLines?: number;
  /** Make regex case-insensitive */
  caseInsensitive?: boolean;
}

/**
 * Trigger instance
 */
export interface Trigger {
  /** Unique trigger ID */
  readonly id: string;

  /**
   * Register a child trigger (active after parent matches)
   * @param pattern - Pattern(s) to match
   * @param callback - Function to call on match
   * @param tag - Optional tag for grouping/removal
   * @param options - Trigger options
   */
  registerChild(
    pattern: TriggerPattern,
    callback?: TriggerCallback,
    tag?: string,
    options?: TriggerOptions
  ): Trigger;

  /**
   * Register a one-time child trigger (auto-removed after first match)
   * @param pattern - Pattern(s) to match
   * @param callback - Function to call on match
   * @param tag - Optional tag for grouping/removal
   * @param options - Trigger options
   */
  registerOneTimeChild(
    pattern: TriggerPattern,
    callback: TriggerCallback,
    tag?: string,
    options?: TriggerOptions
  ): Trigger;
}

/**
 * Helper function to match on line type
 * @param type - Line type to match (e.g., "prompt", "info")
 */
export function isType(type: string): TriggerMatchFunction;

// ============================================================================
// Map Position
// ============================================================================

/**
 * Map direction type
 */
export type MapDirection =
  | "north"
  | "south"
  | "east"
  | "west"
  | "northwest"
  | "northeast"
  | "southeast"
  | "southwest"
  | "up"
  | "down"
  | "in"
  | "out";

/**
 * Map room information
 */
export interface Room {
  /** Room ID */
  id: number;
  /** Area ID (numeric) */
  area: number;
  /** X coordinate */
  x: number;
  /** Y coordinate */
  y: number;
  /** Z coordinate (level) */
  z: number;
  /** Area identifier string */
  areaId: string;
  /** Room name */
  name: string;
  /** Room weight for pathfinding */
  weight: number;
  /** Room symbol */
  symbol: string;
  /** User-defined data */
  userData: Record<string, string>;
  /** Custom lines */
  customLines: Record<string, any>;
  /** Stub exits */
  stubs: number[];
  /** Room hash */
  hash: string;
  /** Environment ID */
  env: number;
  /** Exit connections to room IDs */
  exits: Record<MapDirection, number>;
  /** Door types (1=open, 2=closed, 3=locked) */
  doors: Record<MapDirection, 1 | 2 | 3>;
  /** Special exits with custom commands */
  specialExits: Record<string, number>;
}

// ============================================================================
// Object List Filter Types
// ============================================================================

/**
 * Object data from GMCP
 */
export interface ObjectData {
  num: number;
  id?: string;
  desc?: string;
  hp?: number;
  maxhp?: number;
  image?: string;
  attackers?: { num: number; id?: string }[];
}

/**
 * Entry context provided to filters
 */
export interface EntryContext {
  /** The object data from GMCP */
  object: ObjectData;
  /** The display number/shortcut for this entry */
  displayNum: number;
  /** Whether this is the avatar's current target */
  isTarget: boolean;
  /** Whether this is the avatar's next target in queue */
  isNextTarget: boolean;
  /** Whether this object is a team member */
  isTeammate: boolean;
  /** The raw description text */
  rawDescription: string;
  /** Whether this object is currently attacking */
  isAttacking: boolean;
  /** Current attack command being used */
  attackCommand: string;
}

/**
 * Entry style modifications
 */
export interface EntryStyle {
  /** Color for the description text (CSS color value) */
  descriptionColor?: string;
  /** Whether to apply italic style to description */
  italic?: boolean;
  /** Color for the HP bar (CSS color value) */
  hpBarColor?: string;
  /** Additional CSS class names to add to the entry */
  cssClasses?: string[];
  /** Custom prefix to add before the entry (e.g., icons, indicators) */
  prefix?: string;
  /** Custom suffix to add after the entry */
  suffix?: string;
}

/**
 * Entry content modifications
 */
export interface EntryContent {
  /** Modified description text (replaces original if provided) */
  description?: string;
  /** Modified HP display (replaces original if provided) */
  hpBar?: string;
  /** Modified number label (replaces original if provided) */
  numberLabel?: string;
}

/**
 * Filter result - mutate this object to modify the entry
 */
export interface FilterResult {
  /** Style modifications - mutate this object to add/change styles */
  style: EntryStyle;
  /** Content modifications - mutate this object to replace content */
  content: EntryContent;
  /** If true, prevents subsequent filters from running */
  stopPropagation?: boolean;
}

/**
 * Object list entry filter function
 *
 * Receives context about the entry and the current accumulated result from previous filters.
 * Filters modify the result object directly and optionally return { stopPropagation: true }.
 *
 * @param context - Information about the object being rendered
 * @param result - Current accumulated style and content (mutate this object)
 * @returns void or { stopPropagation: true } to prevent further filters
 *
 * @example
 * \`\`\`typescript
 * const highlightDragons: ObjectListEntryFilter = (context, result) => {
 *   if (context.rawDescription.toLowerCase().includes("smok")) {
 *     result.style.descriptionColor = "#ff0000";
 *     result.style.prefix = (result.style.prefix || "") + "🐉 ";
 *   }
 * };
 *
 * api.objectListFilters.register("dragons", highlightDragons, 10);
 * \`\`\`
 */
export type ObjectListEntryFilter = (
  context: EntryContext,
  result: FilterResult
) => void | { stopPropagation: true };
`);

// Now we need to add the ClientEvents interface
// Read the events file to get the event types
const eventsFilePath = path.join(PROJECT_ROOT, 'src', 'shared', 'events', 'clientEvents.ts');
if (fs.existsSync(eventsFilePath)) {
  const eventsContent = fs.readFileSync(eventsFilePath, 'utf-8');

  output.push(`
// ============================================================================
// Event Types
// ============================================================================

/**
 * Send command event payload
 */
export interface SendCommandEvent {
  command: string;
  echo?: boolean;
  options?: {
    mode?: string;
    [key: string]: any;
  };
}

/**
 * Notification event payload
 */
export interface NotificationPayload {
  text: string;
  time?: number;
}

/**
 * Storage event payload
 */
export interface StorageEventPayload {
  key: string;
  value: unknown;
}

/**
 * Multibind list event payload
 */
export interface MultibindList {
  list: { index: number; action: string; label: string }[];
}

/**
 * Message event payload (output text)
 */
export type MessageEventPayload = [text: string | AnsiAwareBuffer, type?: string, timestamp?: number];

/**
 * Recording auto-stop event payload
 */
export type RecordingAutoStopPayload = [name: string | null, save?: boolean];

/**
 * Playback index event payload
 */
export type PlaybackIndexPayload = [current: number, total: number];

/**
 * Knowledge report action
 */
export type KnowledgeReportAction =
  | { type: "completeLibrary"; libraryId: string }
  | { type: "resetLibrary"; libraryId: string };

/**
 * Package status event payload
 */
export interface PackageStatus {
  recipient: string;
  seconds?: number;
}

/**
 * Plugin loaded event payload
 */
export interface PluginLoadedPayload {
  url: string;
  info: {
    name: string;
    version: string;
    author?: string;
    description?: string;
  };
}

/**
 * Plugin error event payload
 */
export interface PluginErrorPayload {
  url: string;
  error: string;
}

/**
 * Plugin destroyed event payload
 */
export interface PluginDestroyedPayload {
  url: string;
}

/**
 * Clock update event payload
 */
export interface ClockUpdatePayload {
  domain: "Empire" | "Ishtar";
  hours: number;
  minutes: number;
  precision: number;
  sunrise: number | string | "?";
  sunset: number | string | "?";
  dayLabel: string;
  dayOfMonth: number;
  dayOfYear: number;
  daylight?: boolean;
  season?: number;
}

/**
 * Clock domain active event payload
 */
export interface ClockDomainActivePayload {
  domain: "Empire" | "Ishtar";
}

/**
 * Clock mismatch event payload
 */
export interface ClockMismatchPayload {
  domain: "Empire" | "Ishtar";
  type: "sunrise" | "sunset";
  dayOfYear: number;
  expectedHour: number;
  observedHour: number;
  observedMinutes: number;
  indicatedHour?: string;
}

/**
 * Clock sun event payload (sunrise/sunset)
 */
export interface ClockSunEventPayload {
  domain: "Empire" | "Ishtar";
  dayOfYear: number;
  observedHour: number;
  observedMinutes: number;
  indicatedHour?: string;
}

/**
 * Known client events with their payloads
 * Subscribe to these events using api.events.on()
 */
export interface ClientEvents {
  /** Command sent to the MUD server */
  "command": string;
  /** Port connection established */
  "port-connected": void;
  /** Output line sent to display */
  "output-sent": number;
  /** Buffer sent */
  "buffer-sent": number;
  /** Map position changed */
  "mapMove": void;
  /** Step back in location history */
  "stepBack": void;
  /** Lead to specific room ID */
  "leadTo": number;
  /** Clear lead to destination */
  "clearLeadTo": void;
  /** Display notification */
  "notify": NotificationPayload;
  /** Lamp timer updated */
  "lampTimer": number | null;
  /** Cover timer updated */
  "coverTimer": number | null;
  /** Break item warning */
  "breakItem": { text: string; command?: string } | null;
  /** Package delivery status */
  "packageStatus": PackageStatus | null;
  /** Release guard status */
  "releaseGuard": boolean;
  /** Attack mode changed */
  "attackMode": "A" | "AW" | "AWR";
  /** Content width changed */
  "contentWidth": number;
  /** Entered a location. direction is the direction that led to this location (null when set via other means than move) */
  "enterLocation": { id: number; room: unknown; direction: string | null };
  /** Highlights updated */
  "highlights": [number[]];
  /** Multibind list updated */
  "multibinds": MultibindList;
  /** Letter composer state */
  "letterComposer": { open: boolean };
  /** Letter composer submit */
  "letterComposer.submit": unknown;
  /** Letter composer preview */
  "letterComposer.preview": unknown;
  /** NPC information */
  "npc": unknown;
  /** Zask timer status */
  "zaskTimer": { seconds: number; ok: boolean } | null;
  /** Move mode changed */
  "moveModeChanged": number;
  /** Ping measurement */
  "ping": number | null;
  /** Transport timer status */
  "transportTimer": unknown;
  /** Combat timer */
  "combatTimer": number | null;
  /** Team leader target without avatar */
  "teamLeaderTargetNoAvatar": number;
  /** Team leader target with avatar */
  "teamLeaderTargetAvatar": void;
  /** Team composition changed */
  "teamChange": void;
  /** Is team leader status */
  "isTeamLeader": boolean;
  /** Reset client state */
  "reset": void;
  /** Refresh map position when able */
  "refreshPositionWhenAble": void;
  /** Knowledge report */
  "knowledgeReport": unknown | null;
  /** Open knowledge report popup */
  "knowledgeReport.popup.open": void;
  /** Knowledge details report */
  "knowledgeDetailsReport": unknown | null;
  /** Open knowledge details popup */
  "knowledgeDetails.popup.open": void;
  /** Knowledge report action */
  "knowledgeReportAction": KnowledgeReportAction;
  /** Send command to server */
  "sendCommand": SendCommandEvent;
  /** Request herb counts */
  "requestHerbCounts": void;
  /** Herb manager closed */
  "herbManagerClose": void;
  /** Herb counts data */
  "herbCounts": unknown;
  /** Herb manager opened */
  "herbManagerOpen": void;
  /** Play sound effect */
  "sound:play": { key: string };
  /** Play beep sound */
  "playBeep": void;
  /** Line start marker */
  "line-start": void;
  /** Storage value changed */
  "storage": StorageEventPayload;
  /** Settings updated */
  "settings": unknown;
  /** Binds updated */
  "binds": unknown;
  /** UI settings updated */
  "uiSettings": unknown;
  /** Mobile buttons settings updated */
  "mobileButtonsSettings": unknown;
  /** Pauser started */
  "pauserStart": void;
  /** Pauser ended */
  "pauserEnd": void;
  /** Client connected to server */
  "client.connect": void;
  /** Client disconnected from server */
  "client.disconnect": void;
  /** WebSocket opened */
  "open": Event;
  /** WebSocket closed */
  "close": CloseEvent;
  /** Error occurred */
  "error": unknown;
  /** GMCP data received */
  "gmcp": { path: string; value: unknown };
  /** Recording started */
  "recording.start": string;
  /** Recording stopped */
  "recording.stop": boolean | undefined;
  /** Auto-recording started */
  "recording.auto.start": string | null | undefined;
  /** Auto-recording stopped */
  "recording.auto.stop": RecordingAutoStopPayload;
  /** Playback stopped */
  "playback.stop": void;
  /** Playback paused */
  "playback.pause": void;
  /** Playback resumed */
  "playback.resume": void;
  /** Playback started */
  "playback.start": number | undefined;
  /** Playback speed changed */
  "playback.speed": number;
  /** Playback index changed */
  "playback.index": PlaybackIndexPayload;
  /** Message output */
  "message": MessageEventPayload;
  /** Attack queue changed */
  "attackQueueChange": string[];
  /** Clear attack queue */
  "clearAttackQueue": void;
  /** Add to attack queue */
  "addToAttackQueue": string;
  /** Remove from attack queue */
  "removeFromAttackQueue": string;
  /** Objects parsed */
  "parsedObjects": void;
  /** Numbers parsed */
  "parsedNums": { nums: number[] };
  /** Kill event */
  "kill": { killer: "ME" | "TEAM" | "OTHER" };
  /** Enemy killed */
  "enemyKilled": { objNum: number; killer: "ME" | "TEAM" | "OTHER"; hasBody?: boolean };
  /** All enemies killed */
  "allEnemiesKilled": void;
  /** Plugin loaded successfully */
  "plugin:loaded": PluginLoadedPayload;
  /** Plugin error occurred */
  "plugin:error": PluginErrorPayload;
  /** Plugin destroyed */
  "plugin:destroyed": PluginDestroyedPayload;
  /** Clock update */
  "clock.update": ClockUpdatePayload;
  /** Clock domain active */
  "clock.domain.active": ClockDomainActivePayload;
  /** Clock popup opened */
  "clock.popup.open": { domain?: "Empire" | "Ishtar" };
  /** Clock mismatch detected */
  "clock.mismatch": ClockMismatchPayload;
  /** Clock sunrise */
  "clock.sunrise": ClockSunEventPayload;
  /** Clock sunset */
  "clock.sunset": ClockSunEventPayload;
  /** Can wield weapon after knockoff */
  "canWieldAfterKnockOff": void;
  /** Team leader performed special exit follow */
  "followSpecialExit": { exit: string };
  /** GMCP events with dynamic paths (e.g., gmcp.room.info, gmcp.char.vitals) */
  [key: \`gmcp.\${string}\`]: unknown;
  /** GMCP message events */
  [key: \`gmcp_msg.\${string}\`]: AnsiAwareBuffer;
}
`);
}

output.push(`
// ============================================================================
// API Namespaces
// ============================================================================
`);

// Process source file for API interfaces
processNode(sourceFile);

// Add final exports
output.push(`
// ============================================================================
// Exports
// ============================================================================

export default PluginApi;
`);

// Write output file
const finalOutput = output.join('\n');
fs.writeFileSync(OUTPUT_FILE, finalOutput, 'utf-8');

console.log('✅ Type definitions generated successfully!');
console.log(`📦 Exported ${exportedTypes.size} type definitions`);
console.log(`📏 Output size: ${(finalOutput.length / 1024).toFixed(2)} KB`);
