/**
 * TypeScript Type Definitions for Arkadia Web Client Plugins
 *
 * This package provides TypeScript type definitions for developing
 * plugins for the Arkadia Web Client.
 *
 * MAINTAINER NOTE: This file is AUTO-GENERATED from src/client/PluginApi.ts
 * Do not edit this file directly. Run 'yarn build:types' to regenerate.
 *
 * @packageDocumentation
 */


// ============================================================================
// Plugin Interface
// ============================================================================

/**
 * Plugin metadata returned by the init function
 */
export interface PluginInfo {
  /** Name of the plugin */
  name: string;
  /** Version string (e.g., "1.0.0") */
  version: string;
  /** Optional author information */
  author?: string;
  /** Optional description of plugin functionality */
  description?: string;
}

/**
 * Plugin interface that all plugins must implement
 */
export interface Plugin {
  /**
   * Initialize the plugin with access to the Plugin API
   * @param api - The Plugin API instance
   * @returns Promise resolving to plugin metadata
   */
  init(api: PluginApi): Promise<PluginInfo>;

  /**
   * Optional cleanup function called when plugin is unloaded
   */
  destroy?(): Promise<void> | void;
}


// ============================================================================
// Color Types
// ============================================================================

/**
 * Indexed color (0-255)
 */
export interface IndexedColor {
  space: "indexed";
  index: number;
}

/**
 * RGB color
 */
export interface RgbColor {
  space: "rgb";
  r: number;
  g: number;
  b: number;
}

/**
 * Hexadecimal color
 */
export interface HexColor {
  space: "hex";
  color: string;
}

/**
 * Union type for all color formats
 */
export type FormatColor = IndexedColor | RgbColor | HexColor;

/**
 * Hyperlink with callbacks
 */
export interface FormatHyperlink {
  onClick?: (ev: MouseEvent) => void;
  onContextMenu?: (ev: MouseEvent) => void;
  title?: string;
}

/**
 * Complete formatting state for text
 */
export interface FormatStateSnapshot {
  foreground?: FormatColor;
  background?: FormatColor;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  inverse?: boolean;
  strikethrough?: boolean;
  slowBlink?: boolean;
  rapidBlink?: boolean;
  hyperlink?: FormatHyperlink;
}


/**
 * Text range [start, end] for applying formatting
 */
export type TextRange = [start: number, end: number];

/**
 * Buffer segment with text and optional formatting state
 */
export interface BufferSegment {
  text: string;
  state?: FormatStateSnapshot;
}

// ============================================================================
// AnsiAwareBuffer - Line Manipulation
// ============================================================================

/**
 * Buffer for text with ANSI formatting
 * Represents a line of text with color and style information
 */
export declare class AnsiAwareBuffer {
  /**
   * Create a new AnsiAwareBuffer
   * @param initial - Initial text with ANSI codes, array of segments, or undefined
   * @param state - Optional default formatting state
   *
   * @example
   * // Create empty buffer
   * const buffer = new AnsiAwareBuffer();
   *
   * // Create from plain text
   * const buffer = new AnsiAwareBuffer("Hello world");
   *
   * // Create from text with default formatting
   * const buffer = new AnsiAwareBuffer("Hello", api.colors.fromHex('#ff0000'));
   *
   * // Create from ANSI string
   * const buffer = new AnsiAwareBuffer("\x1b[31mRed text\x1b[0m");
   *
   * // Create from segments
   * const segments: BufferSegment[] = [
   *   { text: "Hello ", state: api.colors.fromHex('#00ff00') },
   *   { text: "world", state: api.colors.fromHex('#0000ff') }
   * ];
   * const buffer = new AnsiAwareBuffer(segments);
   */
  constructor(initial?: string | BufferSegment[], state?: FormatStateSnapshot);
  /**
   * Get the plain text content without formatting
   */
  readonly text: string;

  /**
   * Get the total character length
   */
  readonly length: number;

  /**
   * Create a deep copy of this buffer
   */
  clone(): AnsiAwareBuffer;

  /**
   * Clear all content from the buffer
   */
  clear(): this;

  /**
   * Replace text in a range
   * @param range - [start, end] indices
   * @param text - New text to insert
   * @param state - Optional formatting to apply
   */
  replace(range: TextRange, text: string, state?: FormatStateSnapshot): this;

  /**
   * Insert text at an index
   * @param index - Position to insert at
   * @param text - Text to insert
   * @param state - Optional formatting to apply
   */
  insert(index: number, text: string, state?: FormatStateSnapshot): this;

  /**
   * Insert another buffer at an index
   * @param index - Position to insert at
   * @param buffer - Buffer to insert
   */
  insertBuffer(index: number, buffer: AnsiAwareBuffer): this;

  /**
   * Append another buffer to the end
   * @param buffer - Buffer to append
   */
  appendBuffer(buffer: AnsiAwareBuffer): this;

  /**
   * Prepend another buffer to the beginning
   * @param buffer - Buffer to prepend
   */
  prependBuffer(buffer: AnsiAwareBuffer): this;

  /**
   * Add text to the beginning of the line
   * @param text - Text to prepend
   * @param state - Optional formatting to apply
   */
  prepend(text: string, state?: FormatStateSnapshot): this;

  /**
   * Add text to the end of the line
   * @param text - Text to append
   * @param state - Optional formatting to apply
   */
  append(text: string, state?: FormatStateSnapshot): this;

  /**
   * Apply color/formatting to a text range
   * @param range - [start, end] indices
   * @param color - Color index (0-255) or full FormatStateSnapshot
   */
  color(range: TextRange, color: number | FormatStateSnapshot): this;

  /**
   * Apply color/formatting to specific words throughout the buffer
   * @param words - Single word or array of words to colorize
   * @param color - Color index (0-255) or full FormatStateSnapshot
   * @param options - Search options (caseInsensitive)
   *
   * @example
   * ```typescript
   * // Color a single word
   * line.colorWords("gold", api.colors.fromHex('#ffd700'));
   *
   * // Color multiple words
   * line.colorWords(["red", "blue"], 196, { caseInsensitive: true });
   * ```
   */
  colorWords(
    words: string | string[],
    color: number | FormatStateSnapshot,
    options?: { caseInsensitive?: boolean }
  ): this;

  /**
   * Make a text range clickable with event handlers
   * @param range - [start, end] indices
   * @param options - Link options (onClick, onContextMenu, title)
   *
   * @example
   * ```typescript
   * const text = "Click here";
   * const start = line.text.indexOf(text);
   * line.createLink([start, start + text.length], {
   *   onClick: () => api.output.print("Clicked!", "system"),
   *   title: "Click to execute"
   * });
   * ```
   */
  createLink(
    range: TextRange,
    options: {
      onClick?: (ev: MouseEvent) => void;
      onContextMenu?: (ev: MouseEvent) => void;
      title?: string;
    }
  ): this;

  /**
   * Make all occurrences of a text string clickable
   * @param text - Text to make clickable
   * @param options - Link options (onClick, onContextMenu, title)
   * @param searchOptions - Search options (caseInsensitive)
   *
   * @example
   * ```typescript
   * line.createLinksForText("potion", {
   *   onClick: () => api.output.print("Use potion", "system"),
   *   title: "Click to use"
   * }, { caseInsensitive: true });
   * ```
   */
  createLinksForText(
    text: string,
    options: {
      onClick?: (ev: MouseEvent) => void;
      onContextMenu?: (ev: MouseEvent) => void;
      title?: string;
    },
    searchOptions?: { caseInsensitive?: boolean }
  ): this;

  /**
   * Remove text in a range
   * @param range - [start, end] indices
   */
  remove(range: TextRange): this;
  
  /**
     * Returns the format state at the given character index.
     * This includes color information (foreground, background) and other formatting attributes.
     * Returns undefined if the character at that index has no formatting.
     */
    getStateAt(index: number): FormatStateSnapshot | undefined;
}

// ============================================================================
// Trigger System
// ============================================================================

/**
 * Callback function for triggers
 * @param line - The line buffer to potentially modify
 * @param matches - Regex match results
 * @param type - Line type (e.g., "prompt", "info", "error")
 * @returns Modified line or null to suppress the line
 */
export type TriggerCallback = (
  line: AnsiAwareBuffer,
  matches: RegExpMatchArray,
  type: string
) => AnsiAwareBuffer | null;

/**
 * Custom match function for advanced trigger patterns
 */
export type TriggerMatchFunction = (
  line: AnsiAwareBuffer,
  matches: RegExpMatchArray,
  type: string
) => RegExpMatchArray | undefined;

/**
 * Trigger pattern types
 */
export type TriggerSubPattern = string | RegExp | TriggerMatchFunction;
export type TriggerPattern = TriggerSubPattern | TriggerSubPattern[];

/**
 * Options for trigger behavior
 */
export interface TriggerOptions {
  /** Number of lines to keep child triggers active after parent matches */
  stayOpenLines?: number;
  /** Make regex case-insensitive */
  caseInsensitive?: boolean;
}

/**
 * Trigger instance
 */
export interface Trigger {
  /** Unique trigger ID */
  readonly id: string;

  /**
   * Register a child trigger (active after parent matches)
   * @param pattern - Pattern(s) to match
   * @param callback - Function to call on match
   * @param tag - Optional tag for grouping/removal
   * @param options - Trigger options
   */
  registerChild(
    pattern: TriggerPattern,
    callback?: TriggerCallback,
    tag?: string,
    options?: TriggerOptions
  ): Trigger;

  /**
   * Register a one-time child trigger (auto-removed after first match)
   * @param pattern - Pattern(s) to match
   * @param callback - Function to call on match
   * @param tag - Optional tag for grouping/removal
   * @param options - Trigger options
   */
  registerOneTimeChild(
    pattern: TriggerPattern,
    callback: TriggerCallback,
    tag?: string,
    options?: TriggerOptions
  ): Trigger;
}

/**
 * Helper function to match on line type
 * @param type - Line type to match (e.g., "prompt", "info")
 */
export function isType(type: string): TriggerMatchFunction;

// ============================================================================
// Map Position
// ============================================================================

/**
 * Map direction type
 */
export type MapDirection =
  | "north"
  | "south"
  | "east"
  | "west"
  | "northwest"
  | "northeast"
  | "southeast"
  | "southwest"
  | "up"
  | "down"
  | "in"
  | "out";

/**
 * Map room information
 */
export interface Room {
  /** Room ID */
  id: number;
  /** Area ID (numeric) */
  area: number;
  /** X coordinate */
  x: number;
  /** Y coordinate */
  y: number;
  /** Z coordinate (level) */
  z: number;
  /** Area identifier string */
  areaId: string;
  /** Room name */
  name: string;
  /** Room weight for pathfinding */
  weight: number;
  /** Room symbol */
  symbol: string;
  /** User-defined data */
  userData: Record<string, string>;
  /** Custom lines */
  customLines: Record<string, any>;
  /** Stub exits */
  stubs: number[];
  /** Room hash */
  hash: string;
  /** Environment ID */
  env: number;
  /** Exit connections to room IDs */
  exits: Record<MapDirection, number>;
  /** Door types (1=open, 2=closed, 3=locked) */
  doors: Record<MapDirection, 1 | 2 | 3>;
  /** Special exits with custom commands */
  specialExits: Record<string, number>;
}

// ============================================================================
// Object List Filter Types
// ============================================================================

/**
 * Object data from GMCP
 */
export interface ObjectData {
  num: number;
  id?: string;
  desc?: string;
  hp?: number;
  maxhp?: number;
  image?: string;
  attackers?: { num: number; id?: string }[];
}

/**
 * Entry context provided to filters
 */
export interface EntryContext {
  /** The object data from GMCP */
  object: ObjectData;
  /** The display number/shortcut for this entry */
  displayNum: number;
  /** Whether this is the avatar's current target */
  isTarget: boolean;
  /** Whether this is the avatar's next target in queue */
  isNextTarget: boolean;
  /** Whether this object is a team member */
  isTeammate: boolean;
  /** The raw description text */
  rawDescription: string;
  /** Whether this object is currently attacking */
  isAttacking: boolean;
  /** Current attack command being used */
  attackCommand: string;
}

/**
 * Entry style modifications
 */
export interface EntryStyle {
  /** Color for the description text (CSS color value) */
  descriptionColor?: string;
  /** Whether to apply italic style to description */
  italic?: boolean;
  /** Color for the HP bar (CSS color value) */
  hpBarColor?: string;
  /** Additional CSS class names to add to the entry */
  cssClasses?: string[];
  /** Custom prefix to add before the entry (e.g., icons, indicators) */
  prefix?: string;
  /** Custom suffix to add after the entry */
  suffix?: string;
}

/**
 * Entry content modifications
 */
export interface EntryContent {
  /** Modified description text (replaces original if provided) */
  description?: string;
  /** Modified HP display (replaces original if provided) */
  hpBar?: string;
  /** Modified number label (replaces original if provided) */
  numberLabel?: string;
}

/**
 * Filter result - mutate this object to modify the entry
 */
export interface FilterResult {
  /** Style modifications - mutate this object to add/change styles */
  style: EntryStyle;
  /** Content modifications - mutate this object to replace content */
  content: EntryContent;
  /** If true, prevents subsequent filters from running */
  stopPropagation?: boolean;
}

/**
 * Object list entry filter function
 *
 * Receives context about the entry and the current accumulated result from previous filters.
 * Filters modify the result object directly and optionally return { stopPropagation: true }.
 *
 * @param context - Information about the object being rendered
 * @param result - Current accumulated style and content (mutate this object)
 * @returns void or { stopPropagation: true } to prevent further filters
 *
 * @example
 * ```typescript
 * const highlightDragons: ObjectListEntryFilter = (context, result) => {
 *   if (context.rawDescription.toLowerCase().includes("smok")) {
 *     result.style.descriptionColor = "#ff0000";
 *     result.style.prefix = (result.style.prefix || "") + "🐉 ";
 *   }
 * };
 *
 * api.objectListFilters.register("dragons", highlightDragons, 10);
 * ```
 */
export type ObjectListEntryFilter = (
  context: EntryContext,
  result: FilterResult
) => void | { stopPropagation: true };


// ============================================================================
// Event Types
// ============================================================================

/**
 * Send command event payload
 */
export interface SendCommandEvent {
  command: string;
  echo?: boolean;
  options?: {
    mode?: string;
    [key: string]: any;
  };
}

/**
 * Notification event payload
 */
export interface NotificationPayload {
  text: string;
  time?: number;
}

/**
 * Storage event payload
 */
export interface StorageEventPayload {
  key: string;
  value: unknown;
}

/**
 * Multibind list event payload
 */
export interface MultibindList {
  list: { index: number; action: string; label: string }[];
}

/**
 * Message event payload (output text)
 */
export type MessageEventPayload = [text: string | AnsiAwareBuffer, type?: string, timestamp?: number];

/**
 * Recording auto-stop event payload
 */
export type RecordingAutoStopPayload = [name: string | null, save?: boolean];

/**
 * Playback index event payload
 */
export type PlaybackIndexPayload = [current: number, total: number];

/**
 * Knowledge report action
 */
export type KnowledgeReportAction =
  | { type: "completeLibrary"; libraryId: string }
  | { type: "resetLibrary"; libraryId: string };

/**
 * Package status event payload
 */
export interface PackageStatus {
  recipient: string;
  seconds?: number;
}

/**
 * Plugin loaded event payload
 */
export interface PluginLoadedPayload {
  url: string;
  info: {
    name: string;
    version: string;
    author?: string;
    description?: string;
  };
}

/**
 * Plugin error event payload
 */
export interface PluginErrorPayload {
  url: string;
  error: string;
}

/**
 * Plugin destroyed event payload
 */
export interface PluginDestroyedPayload {
  url: string;
}

/**
 * Clock update event payload
 */
export interface ClockUpdatePayload {
  domain: "Empire" | "Ishtar";
  hours: number;
  minutes: number;
  precision: number;
  sunrise: number | string | "?";
  sunset: number | string | "?";
  dayLabel: string;
  dayOfMonth: number;
  dayOfYear: number;
  daylight?: boolean;
  season?: number;
}

/**
 * Clock domain active event payload
 */
export interface ClockDomainActivePayload {
  domain: "Empire" | "Ishtar";
}

/**
 * Clock mismatch event payload
 */
export interface ClockMismatchPayload {
  domain: "Empire" | "Ishtar";
  type: "sunrise" | "sunset";
  dayOfYear: number;
  expectedHour: number;
  observedHour: number;
  observedMinutes: number;
  indicatedHour?: string;
}

/**
 * Clock sun event payload (sunrise/sunset)
 */
export interface ClockSunEventPayload {
  domain: "Empire" | "Ishtar";
  dayOfYear: number;
  observedHour: number;
  observedMinutes: number;
  indicatedHour?: string;
}

/**
 * Known client events with their payloads
 * Subscribe to these events using api.events.on()
 */
export interface ClientEvents {
  /** Command sent to the MUD server */
  "command": string;
  /** Port connection established */
  "port-connected": void;
  /** Output line sent to display */
  "output-sent": number;
  /** Buffer sent */
  "buffer-sent": number;
  /** Map position changed */
  "mapMove": void;
  /** Map data loaded and ready (fired once, after initial map initialization) */
  "mapReady": void;
  /** Step back in location history */
  "stepBack": void;
  /** Lead to specific room ID */
  "leadTo": number;
  /** Clear lead to destination */
  "clearLeadTo": void;
  /** Display notification */
  "notify": NotificationPayload;
  /** Lamp timer updated */
  "lampTimer": number | null;
  /** Cover timer updated */
  "coverTimer": number | null;
  /** Break item warning */
  "breakItem": { text: string; command?: string } | null;
  /** Package delivery status */
  "packageStatus": PackageStatus | null;
  /** Release guard status */
  "releaseGuard": boolean;
  /** Attack mode changed */
  "attackMode": "A" | "AW" | "AWR";
  /** Content width changed */
  "contentWidth": number;
  /** Entered a location. direction is the direction that led to this location (null when set via other means than move) */
  "enterLocation": { id: number; room: unknown; direction: string | null };
  /** Highlights updated */
  "highlights": [number[]];
  /** Multibind list updated */
  "multibinds": MultibindList;
  /** Letter composer state */
  "letterComposer": { open: boolean };
  /** Letter composer submit */
  "letterComposer.submit": unknown;
  /** Letter composer preview */
  "letterComposer.preview": unknown;
  /** NPC information */
  "npc": unknown;
  /** Zask timer status */
  "zaskTimer": { seconds: number; ok: boolean } | null;
  /** Move mode changed */
  "moveModeChanged": number;
  /** Ping measurement */
  "ping": number | null;
  /** Transport timer status */
  "transportTimer": unknown;
  /** Combat timer */
  "combatTimer": number | null;
  /** Team leader target without avatar */
  "teamLeaderTargetNoAvatar": number;
  /** Team leader target with avatar */
  "teamLeaderTargetAvatar": void;
  /** Team composition changed */
  "teamChange": void;
  /** Is team leader status */
  "isTeamLeader": boolean;
  /** Reset client state */
  "reset": void;
  /** Refresh map position when able */
  "refreshPositionWhenAble": void;
  /** Knowledge report */
  "knowledgeReport": unknown | null;
  /** Open knowledge report popup */
  "knowledgeReport.popup.open": void;
  /** Knowledge details report */
  "knowledgeDetailsReport": unknown | null;
  /** Open knowledge details popup */
  "knowledgeDetails.popup.open": void;
  /** Knowledge report action */
  "knowledgeReportAction": KnowledgeReportAction;
  /** Send command to server */
  "sendCommand": SendCommandEvent;
  /** Request herb counts */
  "requestHerbCounts": void;
  /** Herb manager closed */
  "herbManagerClose": void;
  /** Herb counts data */
  "herbCounts": unknown;
  /** Herb manager opened */
  "herbManagerOpen": void;
  /** Play sound effect */
  "sound:play": { key: string };
  /** Play beep sound */
  "playBeep": void;
  /** Line start marker */
  "line-start": void;
  /** Storage value changed */
  "storage": StorageEventPayload;
  /** Settings updated */
  "settings": unknown;
  /** Binds updated */
  "binds": unknown;
  /** UI settings updated */
  "uiSettings": unknown;
  /** Mobile buttons settings updated */
  "mobileButtonsSettings": unknown;
  /** Pauser started */
  "pauserStart": void;
  /** Pauser ended */
  "pauserEnd": void;
  /** Client connected to server */
  "client.connect": void;
  /** Client disconnected from server */
  "client.disconnect": void;
  /** WebSocket opened */
  "open": Event;
  /** WebSocket closed */
  "close": CloseEvent;
  /** Error occurred */
  "error": unknown;
  /** GMCP data received */
  "gmcp": { path: string; value: unknown };
  /** Recording started */
  "recording.start": string;
  /** Recording stopped */
  "recording.stop": boolean | undefined;
  /** Auto-recording started */
  "recording.auto.start": string | null | undefined;
  /** Auto-recording stopped */
  "recording.auto.stop": RecordingAutoStopPayload;
  /** Playback stopped */
  "playback.stop": void;
  /** Playback paused */
  "playback.pause": void;
  /** Playback resumed */
  "playback.resume": void;
  /** Playback started */
  "playback.start": number | undefined;
  /** Playback speed changed */
  "playback.speed": number;
  /** Playback index changed */
  "playback.index": PlaybackIndexPayload;
  /** Message output */
  "message": MessageEventPayload;
  /** Attack queue changed */
  "attackQueueChange": string[];
  /** Clear attack queue */
  "clearAttackQueue": void;
  /** Add to attack queue */
  "addToAttackQueue": string;
  /** Remove from attack queue */
  "removeFromAttackQueue": string;
  /** Objects parsed */
  "parsedObjects": void;
  /** Numbers parsed */
  "parsedNums": { nums: number[] };
  /** Kill event */
  "kill": { killer: "ME" | "TEAM" | "OTHER" };
  /** Enemy killed */
  "enemyKilled": { objNum: number; killer: "ME" | "TEAM" | "OTHER"; hasBody?: boolean };
  /** All enemies killed */
  "allEnemiesKilled": void;
  /** Plugin loaded successfully */
  "plugin:loaded": PluginLoadedPayload;
  /** Plugin error occurred */
  "plugin:error": PluginErrorPayload;
  /** Plugin destroyed */
  "plugin:destroyed": PluginDestroyedPayload;
  /** Clock update */
  "clock.update": ClockUpdatePayload;
  /** Clock domain active */
  "clock.domain.active": ClockDomainActivePayload;
  /** Clock popup opened */
  "clock.popup.open": { domain?: "Empire" | "Ishtar" };
  /** Clock mismatch detected */
  "clock.mismatch": ClockMismatchPayload;
  /** Clock sunrise */
  "clock.sunrise": ClockSunEventPayload;
  /** Clock sunset */
  "clock.sunset": ClockSunEventPayload;
  /** Can wield weapon after knockoff */
  "canWieldAfterKnockOff": void;
  /** Team leader performed special exit follow */
  "followSpecialExit": { exit: string };
  /** GMCP events with dynamic paths (e.g., gmcp.room.info, gmcp.char.vitals) */
  [key: `gmcp.${string}`]: unknown;
  /** GMCP message events */
  [key: `gmcp_msg.${string}`]: AnsiAwareBuffer;
}


// ============================================================================
// API Namespaces
// ============================================================================


/**
 * Valid event names from ClientEvents
 */

export // Event system types
/**
 * Valid event names from ClientEvents
 */
export type EventKey = keyof ClientEvents;

/**
 * Event parameters for a given event key
 */

export type EventParams<K extends EventKey> = [
    ClientEvents[K]
] extends [
    void
] ? [
] : [
    ClientEvents[K]
] extends [
    any[]
] ? ClientEvents[K] : [
    ClientEvents[K]
];

/**
 * Event listener function type for a given event key
 */

export type EventListener<K extends EventKey> = (...args: EventParams<K>) => void;

/**
 * Triggers API - Manage pattern-based triggers
 */

export interface TriggersApi {
    /**
     * Register a trigger that fires when a pattern matches
     * @param pattern - Pattern(s) to match
     * @param callback - Function to call on match
     * @param tag - Optional tag for grouping/removal
     * @param options - Trigger options
     * @returns The registered trigger instance
     */
    register(pattern: TriggerPattern, callback?: TriggerCallback, tag?: string, options?: TriggerOptions): Trigger;
    /**
     * Register a one-time trigger (auto-removed after first match)
     * @param pattern - Pattern(s) to match
     * @param callback - Function to call on match
     * @param tag - Optional tag for grouping/removal
     * @param options - Trigger options
     * @returns The registered trigger instance
     */
    registerOneTime(pattern: TriggerPattern, callback: TriggerCallback, tag?: string, options?: TriggerOptions): Trigger;
    /**
     * Register a token-based trigger (matches whole words/tokens)
     * Token triggers are optimized for matching whole words rather than regex patterns.
     * They split the line into tokens and match complete token sequences.
     * @param token - Token or phrase to match (will be split by spaces/punctuation)
     * @param callback - Function to call on match
     * @param tag - Optional tag for grouping/removal
     * @param options - Trigger options
     * @returns The registered trigger instance
     *
     * @example
     * ```typescript
     * // Match single word
     * api.triggers.registerToken("zloto", (line, matches) => {
     *   return line.color([0, line.text.length], api.colors.fromHex('#ffd700'));
     * }, "myPlugin");
     *
     * // Match phrase (multiple tokens)
     * api.triggers.registerToken("magiczny miecz", (line, matches) => {
     *   api.output.print("Found magic sword!", "system");
     *   return line;
     * }, "myPlugin");
     * ```
     */
    registerToken(token: string, callback?: TriggerCallback, tag?: string, options?: TriggerOptions): Trigger;
    /**
     * Remove a specific trigger
     * @param trigger - Trigger instance to remove
     */
    remove(trigger: Trigger): void;
    /**
     * Remove all triggers with a specific tag
     * @param tag - Tag to filter by
     */
    removeByTag(tag: string): void;
}

/**
 * Aliases API - Manage command aliases
 */

export interface AliasesApi {
    /**
     * Register a command alias
     * @param pattern - Regex pattern to match user input
     * @param callback - Function to execute when pattern matches
     * @returns Alias ID for later removal
     */
    register(pattern: RegExp, callback: (matches?: RegExpMatchArray) => boolean): string;
    /**
     * Remove a command alias by ID
     * @param id - Alias ID returned from register
     */
    remove(id: string): void;
}

/**
 * Events API - Subscribe to and emit events
 */

export interface EventsApi {
    /**
     * Subscribe to an event
     * @param event - Event name (see ClientEvents for available events)
     * @param listener - Event listener function
     * @param options - Listener options (once, signal)
     *
     * @example
     * ```typescript
     * // Subscribe to map movement
     * api.events.on("mapMove", () => {
     *   console.log("Player moved!");
     * });
     *
     * // Subscribe to GMCP with typed payload
     * api.events.on("gmcp", (data) => {
     *   console.log("GMCP:", data.path, data.value);
     * });
     *
     * // Subscribe to specific GMCP path
     * api.events.on("gmcp.room.info", (roomData) => {
     *   console.log("Room info:", roomData);
     * });
     * ```
     */
    on<K extends EventKey>(event: K, listener: EventListener<K>, options?: boolean | {
        once?: boolean;
        signal?: AbortSignal;
    }): void;
    /**
     * Unsubscribe from an event
     * @param event - Event name
     * @param listener - Event listener function to remove
     */
    off<K extends EventKey>(event: K, listener: EventListener<K>): void;
    /**
     * Emit an event
     * @param event - Event name
     * @param args - Event arguments
     *
     * @example
     * ```typescript
     * // Emit a notification
     * api.events.emit("notify", { text: "Hello!", time: 5000 });
     *
     * // Send a command
     * api.events.emit("sendCommand", { command: "look", echo: true });
     * ```
     */
    emit<K extends EventKey>(event: K, ...args: EventParams<K>): void;
}

/**
 * Options for creating a location highlighter
 */

export interface LocationHighlighterOptions {
    /** Highlight color (CSS color string). Defaults to "yellow" */
    color?: string;
    /** Whether the highlighter starts enabled. Defaults to true */
    enabled?: boolean;
}

/**
 * Map API - Access and modify map location
 */

export interface MapApi {
    /**
     * Get current room information
     * @returns Current room with full details or undefined if not in a room
     *
     * @example
     * const room = api.map.getRoom();
     * if (room) {
     *   console.log(`Current room: ${room.name} (${room.id})`);
     *   console.log(`Coordinates: ${room.x}, ${room.y}, ${room.z}`);
     *   console.log(`Area: ${room.areaId}`);
     * }
     */
    getRoom(): MapData.Room | undefined;
    /**
     * Get room information by ID
     * @param roomId - Room ID to look up
     * @returns Room with full details or null if not found
     *
     * @example
     * const room = api.map.getRoomById(12345);
     * if (room) {
     *   console.log(`Room: ${room.name} (${room.id})`);
     *   console.log(`Hash: ${room.hash}`);
     * }
     */
    getRoomById(roomId: number): MapData.Room | null;
    /**
     * Get all areas with their rooms
     * @returns Array of area information objects
     *
     * @example
     * const areas = api.map.getAreas();
     * areas.forEach(area => {
     *   console.log(`Area: ${area.areaName} (${area.areaId})`);
     *   console.log(`Rooms: ${area.rooms.length}`);
     * });
     */
    getAreas(): AreaInfo[];
    /**
     * Find shortest path between two rooms
     * @param fromId - Starting room ID
     * @param toId - Destination room ID
     * @returns Array of room IDs representing the path, or null if no path exists
     *
     * @example
     * const path = api.map.findPath(100, 200);
     * if (path) {
     *   console.log(`Path length: ${path.length - 1} steps`);
     *   console.log(`Route: ${path.join(" -> ")}`);
     * }
     */
    findPath(fromId: number, toId: number): number[] | null;
    /**
     * Set map location programmatically
     * @param roomId - Room ID to navigate to
     *
     * @example
     * api.map.setLocation(12345);
     */
    setLocation(roomId: number): void;
    /**
     * Step back to previous map location
     *
     * @example
     * api.map.stepBack();
     */
    stepBack(): void;
    /**
     * Create a location highlighter for highlighting rooms on the map.
     * Multiple highlighters can exist simultaneously with different colors.
     * Each highlighter can be enabled/disabled independently.
     *
     * @param options - Optional configuration for the highlighter
     * @returns A LocationHighlighter instance
     *
     * @example
     * // Create a red highlighter for quest locations
     * const questHighlighter = api.map.createHighlighter({ color: "red" });
     * questHighlighter.add([100, 200, 300]);
     *
     * // Create a blue highlighter for shops
     * const shopHighlighter = api.map.createHighlighter({ color: "blue" });
     * shopHighlighter.add([400, 500]);
     *
     * // Toggle visibility
     * questHighlighter.disable();
     * questHighlighter.enable();
     *
     * // Clean up when done
     * questHighlighter.destroy();
     */
    createHighlighter(options?: LocationHighlighterOptions): LocationHighlighter;
}

/**
 * Output API - Print to game window
 */

export interface OutputApi {
    /**
     * Print text to the game output
     * @param text - Text or buffer to display
     */
    print(text: string | AnsiAwareBuffer): void;
}

/**
 * Popup content that can be rendered inside plugin popups.
 * Can be:
 * - string: HTML string rendered via dangerouslySetInnerHTML
 * - Node: DOM node appended to container
 * - React.ReactNode: React component/element rendered directly
 */

export type PopupContent = string | Node | React.ReactNode;

/**
 * Handle returned when creating a popup window
 */

export interface PopupHandle {
    /**
     * Root popup element (for further customization)
     */
    readonly element: HTMLDivElement;
    /**
     * Check if popup is pinned
     */
    readonly isPinned: boolean;
    /**
     * Update popup title
     */
    setTitle(title: string): void;
    /**
     * Update popup body content
     */
    setBody(content: PopupContent): void;
    /**
     * Set pinned state
     */
    setPinned(pinned: boolean): void;
    /**
     * Register a callback to be called when popup closes
     * @param callback - Function to call when popup closes
     */
    onClose(callback: () => void): void;
    /**
     * Close and remove the popup
     */
    close(): void;
}

/**
 * Handle returned when registering a persistent popup.
 * Extends PopupHandle with additional persistence features.
 */

export interface PersistentPopupHandle extends PopupHandle {
    /**
     * The stable popup ID (namespaced by plugin)
     */
    readonly id: string;
    /**
     * Whether this popup was restored from a previous session.
     * True if the popup was docked or pinned when the page was last closed.
     */
    readonly wasRestored: boolean;
    /**
     * Whether the popup is currently open
     */
    readonly isOpen: boolean;
    /**
     * Open the popup (if closed).
     * Calls createContent() to generate fresh content.
     */
    open(): Promise<void>;
    /**
     * Update the header actions (buttons displayed in popup header)
     * @param actions - DOM node or React element for header actions
     */
    setHeaderActions(actions: Node | React.ReactNode): void;
}

/**
 * Handle for popup menu entries
 */

export interface PopupMenuEntryHandle {
    /**
     * Update the entry label
     * @param label - String or DOM node for rich content
     */
    setLabel(label: string | Node): void;
    /**
     * Enable or disable the entry
     */
    setDisabled(disabled: boolean): void;
    /**
     * Remove the entry from the menu
     */
    remove(): void;
}

/**
 * Handle for context menu entries
 */

export interface ContextMenuEntryHandle {
    /**
     * Update the entry label
     * @param label - String or DOM node for rich content
     */
    setLabel(label: string | Node): void;
    /**
     * Update the entry action
     */
    setAction(action: () => void): void;
    /**
     * Remove the entry from the menu
     */
    remove(): void;
}

/**
 * Handle for footer components
 */

export interface FooterComponentHandle {
    /**
     * The DOM element for this footer component.
     * Can be used for direct DOM manipulation when using HTML or DOM node content.
     */
    readonly element: HTMLSpanElement;
    /**
     * Update the component content.
     * Accepts HTML strings, DOM nodes, or React elements.
     * When using React, the component will be re-rendered with the new element.
     * @param content - HTML string, DOM node, or React element
     */
    setContent(content: string | Node | ReactElement): void;
    /**
     * Set component visibility
     * @param visible - Whether the component should be visible
     */
    setVisible(visible: boolean): void;
    /**
     * Remove the component from the footer
     */
    remove(): void;
}

/**
 * UI helpers for plugins
 */

export interface UiApi {
    /**
     * Create a draggable popup window.
     *
     * @deprecated Use {@link registerPersistentPopup} instead for popups that need
     * docking and persistence across page reloads. This method generates popup IDs
     * from title hashes, which are not stable and prevent proper state restoration.
     *
     * @param title - Popup title text
     * @param body - Popup body content (string or DOM node)
     * @returns Promise that resolves with handle for controlling the popup once mounted
     */
    createPopup(title: string, body: PopupContent): Promise<PopupHandle>;
    /**
     * Register a persistent popup that can be docked and restored on page reload.
     *
     * If the popup was docked or pinned in a previous session, it will be
     * automatically opened when this method is called. The `wasRestored` property
     * on the returned handle indicates whether this happened.
     *
     * @param config - Popup configuration including ID, title, and content factory
     * @returns Promise that resolves with handle for controlling the popup
     *
     * @example
     * ```typescript
     * const popup = await api.ui.registerPersistentPopup({
     *   id: 'myInventory',
     *   title: 'My Inventory',
     *   createContent: async () => {
     *     const items = await loadInventoryData();
     *     return createInventoryView(items);
     *   }
     * });
     *
     * // Check if popup was restored from previous session
     * if (popup.wasRestored) {
     *   console.log('Popup was restored');
     * }
     *
     * // Toggle popup with menu entry
     * api.ui.addPopupMenuEntry('My Inventory', () => {
     *   popup.isOpen ? popup.close() : popup.open();
     * });
     * ```
     */
    registerPersistentPopup(config: PersistentPopupConfig): Promise<PersistentPopupHandle>;
    /**
     * Add an entry to the popup (⋮) menu
     * @param label - Entry label (string or DOM node for rich content like SVG icons)
     * @param onSelect - Callback invoked when entry is selected
     * @returns Handle for updating or removing the entry
     */
    addPopupMenuEntry(label: string | Node, onSelect: () => void): PopupMenuEntryHandle;
    /**
     * Add an entry to the output context menu
     * @param label - Entry label (string or DOM node for rich content like SVG icons)
     * @param action - Callback invoked when entry is selected
     * @returns Handle for updating or removing the entry
     */
    addContextMenuEntry(label: string | Node, action: () => void): ContextMenuEntryHandle;
    /**
     * Register a footer bar component.
     * Adds a custom component to the footer bar (next to built-in components like
     * Rozkaz timer, Clock, Attack mode, etc.)
     *
     * Supports three content types:
     * - HTML strings: Simple inline HTML
     * - DOM nodes: Pre-created DOM elements
     * - React elements: Full React components with state and hooks
     *
     * @param id - Unique identifier for this component (will be namespaced by plugin)
     * @param content - HTML string, DOM node, or React element
     * @param position - Where to insert: 'start', 'end' (default), or numeric index
     * @returns Handle for updating, hiding, or removing the component
     *
     * @example
     * ```typescript
     * // Simple HTML string
     * const timer = api.ui.registerFooterComponent(
     *   'myTimer',
     *   '<span style="color: yellow;">Timer: 0</span>'
     * );
     *
     * // Update content periodically
     * let seconds = 0;
     * setInterval(() => {
     *   seconds++;
     *   timer.setContent(`<span style="color: yellow;">Timer: ${seconds}</span>`);
     * }, 1000);
     * ```
     *
     * @example
     * ```typescript
     * // DOM node
     * const statusSpan = document.createElement('span');
     * statusSpan.style.color = 'springgreen';
     * statusSpan.textContent = 'Ready';
     *
     * const status = api.ui.registerFooterComponent('status', statusSpan);
     *
     * // Direct DOM manipulation
     * status.element.style.color = 'red';
     * status.element.textContent = 'Busy';
     * ```
     *
     * @example
     * ```typescript
     * // React component with state
     * import { useState, useEffect } from 'react';
     *
     * const MyTimer: React.FC = () => {
     *   const [seconds, setSeconds] = useState(0);
     *
     *   useEffect(() => {
     *     const interval = setInterval(() => setSeconds(s => s + 1), 1000);
     *     return () => clearInterval(interval);
     *   }, []);
     *
     *   return <span style={{ color: 'yellow' }}>Timer: {seconds}</span>;
     * };
     *
     * // Register React component
     * const timer = api.ui.registerFooterComponent('myTimer', <MyTimer />);
     *
     * // Can also update with new React element
     * timer.setContent(<MyTimer key="reset" />);
     * ```
     *
     * @example
     * ```typescript
     * // React component using client events (like built-in OrderTimer)
     * import { useState } from 'react';
     * import { useClientEvent } from '@web/hooks';
     *
     * const AttackStatus: React.FC = () => {
     *   const [isAttacking, setIsAttacking] = useState(false);
     *
     *   useClientEvent('combatStart', () => setIsAttacking(true));
     *   useClientEvent('combatEnd', () => setIsAttacking(false));
     *
     *   if (!isAttacking) return null;
     *   return <span style={{ color: 'red' }}>COMBAT</span>;
     * };
     *
     * api.ui.registerFooterComponent('attackStatus', <AttackStatus />);
     * ```
     */
    registerFooterComponent(id: string, content: string | Node | ReactElement, position?: 'start' | 'end' | number): FooterComponentHandle;
}

/**
 * Colors API - Create and manage colors
 */

export interface ColorsApi {
    /**
     * Create a color from hex string
     * @param hex - Hex color string (e.g., "#ff0000")
     * @returns Format state with the color applied
     */
    fromHex(hex: string): FormatStateSnapshot;
    /**
     * Create a color from RGB values
     * @param r - Red (0-255)
     * @param g - Green (0-255)
     * @param b - Blue (0-255)
     * @returns Format state with the color applied
     */
    fromRgb(r: number, g: number, b: number): FormatStateSnapshot;
}

/**
 * Function Bind API - Manage keyboard bindings
 */

export interface BindApi {
    /**
     * Set a function bind - binds a command or callback to a key
     * When the configured key is pressed, either the command will be sent
     * or the callback will be executed.
     *
     * @param printable - Command string to execute (or null to just use callback)
     * @param callback - Optional callback function to execute instead of sending command
     * @param clearAfterUse - If true, clear the bind after it's used once
     *
     * @example
     * ```typescript
     * // Bind a command to the function key
     * api.bind.set("attack goblin");
     *
     * // Bind a callback function
     * api.bind.set(null, () => {
     *   api.output.print("Custom action triggered!", "system");
     * });
     *
     * // Bind with auto-clear after use
     * api.bind.set("use potion", undefined, true);
     * ```
     */
    set(printable: string | null, callback?: () => void, clearAfterUse?: boolean): void;
    /**
     * Clear the current function bind
     *
     * @example
     * ```typescript
     * api.bind.clear();
     * ```
     */
    clear(): void;
    /**
     * Get the current bind label (key combination)
     * Returns the configured key combination like "CTRL+]" or "ALT+SHIFT+K"
     *
     * @returns Label string representing the key combination
     *
     * @example
     * ```typescript
     * const label = api.bind.getLabel();
     * api.output.print(`Function bind key: ${label}`, "system");
     * ```
     */
    getLabel(): string;
}

/**
 * Team API - Access team information
 */

export interface TeamApi {
    /**
     * Get list of team member names
     * @returns Array of team member names
     *
     * @example
     * ```typescript
     * const members = api.team.getMembers();
     * api.output.print(`Team has ${members.length} members`, "system");
     * ```
     */
    getMembers(): string[];
    /**
     * Get the team leader's name
     * @returns Leader name or undefined if not in a team
     *
     * @example
     * ```typescript
     * const leader = api.team.getLeader();
     * if (leader) {
     *   api.output.print(`Team leader: ${leader}`, "system");
     * }
     * ```
     */
    getLeader(): string | undefined;
    /**
     * Get the team leader's object ID
     * @returns Leader object ID or undefined if not in a team
     */
    getLeaderId(): number | undefined;
    /**
     * Get the player's object number
     * @returns Player object number or undefined
     */
    getPlayerNum(): number | undefined;
}

/**
 * GMCP API - Access GMCP data
 */

export interface GmcpApi {
    /**
     * Get the current GMCP data object
     * Contains all GMCP data received from the server
     * @returns GMCP data object
     *
     * @example
     * ```typescript
     * const gmcp = api.gmcp.get();
     * const hp = gmcp?.char?.vitals?.hp;
     * const roomName = gmcp?.room?.info?.name;
     * ```
     */
    get(): Record<string, any>;
}

/**
 * Attack Queue API - Manage attack queue
 */

export interface AttackQueueApi {
    /**
     * Add an enemy to the attack queue
     * @param id - Object ID of the enemy
     * @returns True if added successfully, false if already in queue
     *
     * @example
     * ```typescript
     * const added = api.attackQueue.add("12345");
     * if (added) {
     *   api.output.print("Enemy added to queue", "system");
     * }
     * ```
     */
    add(id: number): boolean;
    /**
     * Remove an enemy from the attack queue
     * @param id - Object ID of the enemy
     * @returns True if removed successfully, false if not found
     *
     * @example
     * ```typescript
     * api.attackQueue.remove("12345");
     * ```
     */
    remove(id: number): boolean;
    /**
     * Clear the entire attack queue
     *
     * @example
     * ```typescript
     * api.attackQueue.clear();
     * api.output.print("Attack queue cleared", "system");
     * ```
     */
    clear(): void;
    /**
     * Get the current attack queue
     * @returns Array of enemy object IDs in queue order
     *
     * @example
     * ```typescript
     * const queue = api.attackQueue.get();
     * api.output.print(`Queue has ${queue.length} enemies`, "system");
     * ```
     */
    get(): number[];
}

/**
 * Location object information
 */

export interface LocationObject {
    /** Object number */
    num: number;
    /** Object description/name */
    desc?: string;
    /** HP */
    hp?: number;
    /** Attack number or boolean indicating combat status */
    attack_num?: boolean | number;
    /** Whether avatar is targeting this object */
    avatar_target?: boolean;
    /** Whether this is an attack target */
    attack_target?: boolean;
    /** Whether this is a defense target */
    defense_target?: boolean;
    /** Shortcut key for this object (e.g., '@', 'A', '1') */
    shortcut?: string;
    /** Category: player, team member, enemy, or non-combat entity */
    __category?: 'player' | 'team' | 'rest' | 'rest-noncombat';
}

/**
 * Objects API - Access objects in current location
 */

export interface ObjectsApi {
    /**
     * Get all objects in current location
     * Returns objects organized by category (player, team, enemies, non-combat)
     * with shortcuts assigned for easy targeting
     *
     * @returns Array of location objects with shortcuts and categories
     *
     * @example
     * ```typescript
     * const objects = api.objects.getObjectsOnLocation();
     *
     * // Find player object
     * const player = objects.find(o => o.__category === 'player');
     *
     * // Find all enemies
     * const enemies = objects.filter(o => o.__category === 'rest');
     *
     * // Find object by shortcut
     * const target = objects.find(o => o.shortcut === '1');
     * if (target) {
     *   api.output.print(`Target: ${target.desc} (${target.num})`, "system");
     * }
     * ```
     */
    getObjectsOnLocation(): LocationObject[];
}

/**
 * Command API - Send commands to the server
 */

export interface CommandApi {
    /**
     * Send a command to the server
     * @param command - Command string to send
     * @param echo - Whether to echo the command in the output (default: true)
     * @param options - Additional command options
     *
     * @example
     * ```typescript
     * // Send a simple command
     * api.command.send("look");
     *
     * // Send a command without echoing it
     * api.command.send("attack goblin", false);
     *
     * // Send multiple commands in a sequence
     * await api.command.send("get sword");
     * await api.command.send("wield sword");
     * ```
     */
    send(command: string, echo?: boolean, options?: any): Promise<void>;
    /**
     * Add words to the command line tab-completion suggestions.
     * These suggestions appear alongside words extracted from the output buffer
     * when the user presses Tab in the command input.
     * Duplicate words are ignored.
     *
     * @param words - Words to add as tab-completion suggestions
     *
     * @example
     * ```typescript
     * api.command.addSuggestions("goblin", "dragon", "potezny");
     * ```
     */
    addSuggestions(...words: string[]): void;
    /**
     * Remove words previously added via {@link addSuggestions}.
     *
     * @param words - Words to remove from tab-completion suggestions
     *
     * @example
     * ```typescript
     * api.command.removeSuggestions("goblin");
     * ```
     */
    removeSuggestions(...words: string[]): void;
}

/**
 * Command Hooks API - Intercept and modify commands before processing
 */

export interface CommandHooksApi {
    /**
     * Register a command hook that can alter or suppress commands.
     * Hooks are called early in sendCommand, before any processing
     * (before Polish character stripping, map parsing, alias matching, etc).
     *
     * @param callback - Hook callback function that receives the command and can:
     *   - Return a modified command string to alter the command
     *   - Return null to suppress/cancel the command
     *   - Return undefined to keep the original command unchanged
     * @param priority - Hook priority (higher runs first, default: 0)
     * @returns Hook ID for later removal
     *
     * @example
     * ```typescript
     * // Modify a command
     * const hookId = api.commandHooks.register((command, echo, options) => {
     *   if (command === "atakuj") {
     *     return "atakuj ob_12345"; // Replace with specific target
     *   }
     *   return undefined; // Keep original for other commands
     * });
     *
     * // Suppress a command
     * api.commandHooks.register((command) => {
     *   if (command.startsWith("niebezpieczne")) {
     *     api.output.print("Command blocked!");
     *     return null; // Suppress the command
     *   }
     *   return undefined;
     * });
     *
     * // Later: remove the hook
     * api.commandHooks.unregister(hookId);
     * ```
     */
    register(callback: CommandHookCallback, priority?: number): string;
    /**
     * Unregister a previously registered command hook
     * @param hookId - Hook ID returned from register
     * @returns true if hook was found and removed
     */
    unregister(hookId: string): boolean;
}

/**
 * Group definition for categorizing container items
 */

export interface GroupDefinition {
    /** Group name */
    name: string;
    /** Filter function to check if item belongs to this group */
    filter: (item: string) => boolean;
}

/**
 * Transform definition for styling container items
 */

export interface TransformDefinition {
    /**
     * Transform item buffer with optional formatting
     * @param buffer - The AnsiAwareBuffer containing the item name
     * @param item - The container item with name and count
     * @param group - The group name this item belongs to
     * @returns The buffer (modified or unmodified)
     */
    transform: (buffer: AnsiAwareBuffer, item: {
        name: string;
        count: string | number;
    }, group: string) => AnsiAwareBuffer;
}

/**
 * Herb bag state - contains herbs and optional condition
 */

export interface HerbBagState {
    /** Map of herb ID to count */
    herbs: Record<string, number>;
    /** Bag condition (1-5, where 5 is best) */
    condition?: number;
}

/**
 * All herb bags state - map of bag number to bag state
 */

export type HerbBagsState = Record<number, HerbBagState>;

/**
 * Options for moving herbs between bags
 */

export interface HerbMoveOptions {
    /** Herb ID to move */
    herbId: string;
    /** Amount to move */
    amount: number;
    /** Source bag number */
    fromBag: number;
    /** Destination bag number */
    toBag: number;
}

/**
 * Herb grammatical forms (Polish declensions)
 */

export interface HerbForms {
    /** Nominative singular (mianownik) */
    mianownik: string;
    /** Genitive singular (dopelniacz) */
    dopelniacz: string;
    /** Accusative singular (biernik) */
    biernik: string;
    /** Nominative plural (mnoga mianownik) */
    mnoga_mianownik: string;
    /** Genitive plural (mnoga dopelniacz) */
    mnoga_dopelniacz: string;
    /** Accusative plural (mnoga biernik) */
    mnoga_biernik: string;
}

/**
 * Herb use/effect definition
 */

export interface HerbUse {
    /** Action command (e.g., "jedz", "pal") */
    action: string;
    /** Effect description */
    effect: string;
    /** If true, herb should not be bound when used */
    dont_bind?: boolean;
}

/**
 * Complete herb database structure
 */

export interface HerbsData {
    /** Map of herb ID to grammatical forms */
    herb_id_to_odmiana: Record<string, HerbForms>;
    /** Database version number */
    version: number;
    /** Map of herb ID to array of uses/effects */
    herb_id_to_use: Record<string, HerbUse[]>;
}

/**
 * Pretty Containers API - Access and extend container formatting
 */

export interface PrettyContainersApi {
    /**
     * Get current group definitions for categorizing items
     * Groups determine how items are organized in container displays
     *
     * @returns Read-only array of group definitions
     *
     * @example
     * ```typescript
     * const groups = api.prettyContainers.getFilters();
     * console.log("Available groups:", groups.map(g => g.name));
     * ```
     */
    getFilters(): ReadonlyArray<Readonly<GroupDefinition>>;
    /**
     * Get current transform definitions for styling items
     * Transforms apply colors, links, and formatting to matching items
     *
     * @returns Read-only array of transform definitions
     *
     * @example
     * ```typescript
     * const transforms = api.prettyContainers.getTransforms();
     * console.log(`${transforms.length} transforms registered`);
     * ```
     */
    getTransforms(): ReadonlyArray<Readonly<TransformDefinition>>;
    /**
     * Add a new group definition for categorizing items
     * New groups will appear in container displays
     *
     * @param definition - Group definition with name and filter function
     *
     * @example
     * ```typescript
     * // Add a group for potions
     * api.prettyContainers.addFilter({
     *   name: "mikstury",
     *   filter: (item) => /eliksir|mikstur/.test(item)
     * });
     * ```
     */
    addFilter(definition: GroupDefinition): void;
    /**
     * Add a new transform definition for styling items
     * New transforms will be applied to all items in containers
     *
     * @param definition - Transform definition with transform function
     *
     * @example
     * ```typescript
     * // Highlight potions in green
     * api.prettyContainers.addTransform({
     *   transform: (buffer, item, group) => {
     *     if (/eliksir|mikstur/.test(item.name)) {
     *       buffer.color([0, buffer.length], api.colors.fromHex('#00ff00'));
     *     }
     *     return buffer;
     *   }
     * });
     * ```
     */
    addTransform(definition: TransformDefinition): void;
}

/**
 * Single magic item entry
 */

export interface MagicEntry {
    type: string[];
    regexps?: string[];
}

/**
 * Raw magics data structure
 */

export interface MagicsFile {
    magics: Record<string, MagicEntry>;
}

/**
 * Magics API - Access magic item patterns
 */

export interface MagicsApi {
    /**
     * Get current magic item patterns
     * Returns patterns used to identify magic items in game output
     *
     * @returns Promise resolving to array of regex pattern strings
     *
     * @example
     * ```typescript
     * const patterns = await api.magics.getPatterns();
     * console.log(`${patterns.length} magic patterns loaded`);
     *
     * // Check if an item matches magic patterns
     * const item = "magiczny miecz";
     * const ismagic = patterns.some(p => new RegExp(p, 'i').test(item));
     * ```
     */
    getPatterns(): Promise<string[]>;
    /**
     * Get raw magics data
     * Returns the complete magics data structure with item names, types, and patterns
     *
     * @returns Promise resolving to raw MagicsFile data or undefined if not loaded
     *
     * @example
     * ```typescript
     * const rawData = await api.magics.getRawData();
     * if (rawData) {
     *   for (const [name, magic] of Object.entries(rawData.magics)) {
     *     console.log(`${name}: types=${magic.type.join(',')}, patterns=${magic.regexps?.length || 0}`);
     *   }
     * }
     * ```
     */
    getRawData(): Promise<MagicsFile | undefined>;
}

/**
 * Raw magic keys data structure
 */

export interface MagicKeysData {
    magic_keys: string[];
}

/**
 * Magic Keys API - Access magic key patterns
 */

export interface MagicKeysApi {
    /**
     * Get current magic key patterns
     * Returns patterns used to identify magic keys in game output
     *
     * @returns Promise resolving to array of pattern strings
     *
     * @example
     * ```typescript
     * const patterns = await api.magicKeys.getPatterns();
     * console.log(`${patterns.length} magic key patterns loaded`);
     *
     * // Check if an item is a magic key
     * const item = "klucz ze srebra";
     * const isMagicKey = patterns.some(p => new RegExp(p, 'i').test(item));
     * ```
     */
    getPatterns(): Promise<string[]>;
    /**
     * Get raw magic keys data
     * Returns the complete magic keys data structure
     *
     * @returns Promise resolving to raw MagicKeysData or undefined if not loaded
     *
     * @example
     * ```typescript
     * const rawData = await api.magicKeys.getRawData();
     * if (rawData) {
     *   console.log(`${rawData.magic_keys.length} magic keys loaded`);
     * }
     * ```
     */
    getRawData(): Promise<MagicKeysData | undefined>;
}

/**
 * Container type for bag assignment
 * - "money" - money container
 * - "gems" - gems container
 * - "food" - food container
 * - "other" - general items container
 */

export type ContainerType = "money" | "gems" | "food" | "other";

/**
 * Grammatical forms for a container bag name
 */

export interface ContainerForms {
    /** Nominative form (mianownik) - e.g., "plecak", "torba" */
    mianownik: string;
    /** Genitive form (dopelniacz) - e.g., "plecaka", "torby" */
    dopelniacz: string;
    /** Accusative form (biernik) - e.g., "plecak", "torbe" */
    biernik: string;
}

/**
 * Containers API - Put items into and take items from assigned bags
 */

export interface ContainersApi {
    /**
     * Get the assigned bag name for a container type
     *
     * @param type - Container type ("money", "gems", "food", "other")
     * @returns The bag name (e.g., "plecak", "torba")
     *
     * @example
     * ```typescript
     * const moneyBag = api.containers.getContainer("money");
     * console.log(`Money is stored in: ${moneyBag}`);
     * ```
     */
    getContainer(type: ContainerType): string;
    /**
     * Get grammatical forms for a container type's bag
     * Returns mianownik, dopelniacz, and biernik forms
     *
     * @param type - Container type ("money", "gems", "food", "other")
     * @returns Object with mianownik, dopelniacz, biernik forms, or null if bag is unknown
     *
     * @example
     * ```typescript
     * const forms = api.containers.getContainerForms("other");
     * if (forms) {
     *   console.log(`mianownik: ${forms.mianownik}`);   // "plecak"
     *   console.log(`dopelniacz: ${forms.dopelniacz}`);   // "plecaka"
     *   console.log(`biernik: ${forms.biernik}`);         // "plecak"
     * }
     * ```
     */
    getContainerForms(type: ContainerType): ContainerForms | null;
    /**
     * Put items into a container bag
     * Opens the bag, puts items in, and closes the bag
     *
     * @param type - Container type ("money", "gems", "food", "other")
     * @param item - Item name(s) to put in, comma-separated for multiple
     *
     * @example
     * ```typescript
     * // Put money into money bag
     * api.containers.put("money", "monety");
     *
     * // Put multiple items into other bag
     * api.containers.put("other", "miecz, tarcza");
     * ```
     */
    put(type: ContainerType, item: string): void;
    /**
     * Take items from a container bag
     * Opens the bag, takes items out, and closes the bag
     *
     * @param type - Container type ("money", "gems", "food", "other")
     * @param item - Item name(s) to take out, comma-separated for multiple
     *
     * @example
     * ```typescript
     * // Take money from money bag
     * api.containers.take("money", "monety");
     *
     * // Take multiple items from other bag
     * api.containers.take("other", "miecz, tarcza");
     * ```
     */
    take(type: ContainerType, item: string): void;
}

/**
 * Herbs API - Access herb inventory in bags
 */

export interface HerbsApi {
    /**
     * Get current state of all herb bags
     * Returns a copy of the herb bags state with herb counts and conditions
     *
     * @returns Object mapping bag number to bag state
     *
     * @example
     * ```typescript
     * const bags = api.herbs.getBags();
     * console.log("Bag 1:", bags[1]?.herbs);
     *
     * // Count total herbs
     * const totals: Record<string, number> = {};
     * Object.values(bags).forEach(bag => {
     *   Object.entries(bag.herbs).forEach(([herb, count]) => {
     *     totals[herb] = (totals[herb] || 0) + count;
     *   });
     * });
     * ```
     */
    getBags(): HerbBagsState;
    /**
     * Take herbs from bags
     * Removes herbs from inventory and executes appropriate game commands
     *
     * @param herbId - Herb identifier (e.g., "ziolo_many", "czosnek")
     * @param amount - Number of herbs to take
     * @param fromBag - Optional specific bag number to take from
     * @returns Promise resolving to number of herbs actually taken
     *
     * @example
     * ```typescript
     * // Take 3 herbs from any bag
     * const taken = await api.herbs.take("ziolo_many", 3);
     * console.log(`Took ${taken} ziolo_many`);
     *
     * // Take from specific bag
     * const taken = await api.herbs.take("czosnek", 1, 2);
     * ```
     */
    take(herbId: string, amount: number, fromBag?: number): Promise<number>;
    /**
     * Put herbs into a bag
     * Adds herbs to inventory and executes appropriate game commands
     *
     * @param herbId - Herb identifier
     * @param amount - Number of herbs to put
     * @param bag - Bag number to put herbs into
     * @returns Promise resolving to number of herbs actually put
     *
     * @example
     * ```typescript
     * // Put 5 herbs into bag 1
     * const put = await api.herbs.put("ziolo_many", 5, 1);
     * console.log(`Put ${put} ziolo_many into bag 1`);
     * ```
     */
    put(herbId: string, amount: number, bag: number): Promise<number>;
    /**
     * Move herbs between bags
     * Convenience method that takes from one bag and puts into another
     *
     * @param options - Move options with herbId, amount, fromBag, toBag
     * @returns Promise resolving when move is complete
     *
     * @example
     * ```typescript
     * // Move 3 herbs from bag 1 to bag 2
     * await api.herbs.move({
     *   herbId: "ziolo_many",
     *   amount: 3,
     *   fromBag: 1,
     *   toBag: 2
     * });
     * ```
     */
    move(options: HerbMoveOptions): Promise<void>;
    /**
     * Get the herb database containing herb forms and uses
     * Returns data about herb conjugations (forms) and effects
     *
     * @returns Promise resolving to herb database or null if unavailable
     *
     * @example
     * ```typescript
     * const data = await api.herbs.getData();
     * if (data) {
     *   // Get herb forms for "ziolo_many"
     *   const forms = data.herb_id_to_odmiana["ziolo_many"];
     *   console.log("Nominative:", forms.mianownik);
     *   console.log("Genitive:", forms.dopelniacz);
     *
     *   // Get herb uses
     *   const uses = data.herb_id_to_use["ziolo_many"];
     *   uses?.forEach(use => {
     *     console.log(`Action: ${use.action}, Effect: ${use.effect}`);
     *   });
     * }
     * ```
     */
    getData(): Promise<HerbsData | null>;
}

/**
 * Object List Filters API - Customize object list entry rendering
 *
 * Allows plugins to register filters that modify how objects are displayed
 * in the object list. Filters can change colors, add icons, modify text, etc.
 *
 * Types are available for import:
 * ```typescript
 * import type { ObjectListEntryFilter, EntryContext, FilterResult } from "@web/objectListFilters";
 * ```
 */

export interface ObjectListFiltersApi {
    /**
     * Register an object list entry filter
     *
     * Filters receive context about the object and can modify its appearance
     * by mutating the result parameter. Multiple filters can compose together.
     *
     * @param name - Unique identifier for this filter
     * @param filter - Filter function that modifies entry appearance
     * @param priority - Optional priority (higher = runs first, default: 0)
     *
     * @example
     * ```typescript
     * // Highlight dragons in red with icon
     * api.objectListFilters.register("dragons", (context, result) => {
     *   if (context.rawDescription.toLowerCase().includes("smok")) {
     *     result.style.descriptionColor = "#ff0000";
     *     result.style.prefix = (result.style.prefix || "") + "🐉 ";
     *   }
     * }, 10);
     *
     * // Warn about low HP enemies
     * api.objectListFilters.register("lowHp", (context, result) => {
     *   if (context.object.hp && context.object.maxhp) {
     *     const percent = context.object.hp / context.object.maxhp;
     *     if (percent < 0.2) {
     *       result.style.hpBarColor = "#ff0000";
     *       result.style.suffix = (result.style.suffix || "") + " ☠️";
     *     }
     *   }
     * }, 5);
     * ```
     */
    register(name: string, filter: ObjectListEntryFilter, priority?: number): void;
    /**
     * Unregister an object list entry filter
     *
     * @param name - Filter identifier to remove
     * @returns True if filter was found and removed
     *
     * @example
     * ```typescript
     * api.objectListFilters.unregister("dragons");
     * ```
     */
    unregister(name: string): boolean;
    /**
     * Get list of registered filter names
     *
     * @returns Array of filter names in priority order
     *
     * @example
     * ```typescript
     * const filters = api.objectListFilters.getFilterNames();
     * console.log("Active filters:", filters);
     * ```
     */
    getFilterNames(): string[];
    /**
     * Clear all registered filters
     *
     * @example
     * ```typescript
     * api.objectListFilters.clear();
     * ```
     */
    clear(): void;
}

/**
 * Handle returned by buttonMacros.register() for controlling macro state
 */

export interface ButtonMacroHandle {
    /** Get current state ID (for stateful macros) */
    getState(): string | undefined;
    /** Set state by ID (for stateful macros) */
    setState(stateId: string): boolean;
    /** Cycle to next state, wraps around (for stateful macros) */
    cycleState(): void;
    /**
     * Subscribe to state changes
     * @param listener - Callback when state changes
     * @returns Unsubscribe function
     */
    onStateChange(listener: (newState: string, oldState: string | undefined) => void): () => void;
}

/**
 * Button Macros API - Register custom button macros
 *
 * Allows plugins to define custom macros that can be assigned to mobile and desktop buttons.
 * Macros can be stateless (simple click actions) or stateful (toggle/mode buttons).
 */

export interface ButtonMacrosApi {
    /**
     * Register a custom button macro
     *
     * @param options - Macro configuration
     * @param options.id - Unique identifier (will be prefixed with "plugin:")
     * @param options.label - Display label shown in button configuration
     * @param options.onClick - Handler called when button is clicked
     * @param options.configFields - Optional custom configuration fields
     * @param options.states - For stateful macros: array of possible states
     * @param options.initialState - Initial state ID (defaults to first state)
     *
     * @example Simple macro
     * ```typescript
     * api.buttonMacros.register({
     *   id: "myAction",
     *   label: "My Custom Action",
     *   onClick: (button, client, config) => {
     *     client.sendCommand(config.command || "look");
     *   },
     *   configFields: [
     *     { name: "command", type: "text", label: "Command" }
     *   ]
     * });
     * ```
     *
     * @example Stateful toggle macro
     * ```typescript
     * api.buttonMacros.register({
     *   id: "autoHeal",
     *   label: "Auto Heal Toggle",
     *   states: [
     *     { id: "off", label: "OFF", color: "#666666" },
     *     { id: "on", label: "ON", color: "#00ff00" }
     *   ],
     *   initialState: "off",
     *   onClick: (ctx) => {
     *     // ctx.stateCtx is available for stateful macros
     *     ctx.stateCtx.cycleState(); // Toggle to next state
     *     if (ctx.stateCtx.state === "off") {
     *       // Turning on
     *       ctx.client.sendCommand("autoheal on");
     *     } else {
     *       // Turning off
     *       ctx.client.sendCommand("autoheal off");
     *     }
     *   }
     * });
     * ```
     *
     * @example Stateful mode macro
     * ```typescript
     * api.buttonMacros.register({
     *   id: "combatMode",
     *   label: "Combat Mode",
     *   states: [
     *     { id: "defensive", label: "DEF", color: "#0066ff" },
     *     { id: "balanced", label: "BAL", color: "#ffff00" },
     *     { id: "aggressive", label: "AGR", color: "#ff0000" }
     *   ],
     *   onClick: (ctx) => {
     *     ctx.stateCtx.cycleState();
     *     ctx.client.sendCommand(`combat ${ctx.stateCtx.state}`);
     *   }
     * });
     * ```
     */
    register(options: {
        id: string;
        label: string;
        onClick: ((context: ButtonMacroClickContext) => void) | ((button: MobileButtonSetting, client: Client, config: Record<string, any>) => void);
        configFields?: MacroConfigField[];
        states?: MacroState[];
        initialState?: string;
    }): ButtonMacroHandle;
    /**
     * Unregister a previously registered button macro
     * @param id - Macro ID (without "plugin:" prefix)
     */
    unregister(id: string): void;
    /**
     * Get the current state of a stateful macro
     * @param id - Macro ID (without "plugin:" prefix)
     * @returns Current state ID or undefined if not stateful
     *
     * @example
     * ```typescript
     * const state = api.buttonMacros.getState("autoHeal");
     * if (state === "on") {
     *   // Auto-heal is enabled
     * }
     * ```
     */
    getState(id: string): string | undefined;
    /**
     * Set the state of a stateful macro programmatically
     * This will update all buttons using this macro across the UI
     *
     * @param id - Macro ID (without "plugin:" prefix)
     * @param stateId - State ID to set (must be valid for this macro)
     * @returns True if state was set successfully
     *
     * @example
     * ```typescript
     * // Turn off auto-heal programmatically
     * api.buttonMacros.setState("autoHeal", "off");
     * ```
     */
    setState(id: string, stateId: string): boolean;
    /**
     * Subscribe to state changes for a macro
     * Useful for syncing state with game events
     *
     * @param id - Macro ID (without "plugin:" prefix)
     * @param listener - Callback called when state changes
     * @returns Unsubscribe function
     *
     * @example
     * ```typescript
     * // Listen for auto-heal state changes
     * const unsubscribe = api.buttonMacros.onStateChange("autoHeal", (macroType, newState, oldState) => {
     *   console.log(`Auto-heal changed from ${oldState} to ${newState}`);
     * });
     *
     * // Later: stop listening
     * unsubscribe();
     * ```
     */
    onStateChange(id: string, listener: (macroType: string, newState: string, oldState: string | undefined) => void): () => void;
}

/**
 * Trigger Macros API - Register custom trigger macros
 *
 * Allows plugins to define custom macros that can be used in user triggers.
 */

export interface TriggerMacrosApi {
    /**
     * Register a custom trigger macro
     *
     * @param options - Macro configuration
     * @param options.id - Unique identifier (will be prefixed with "plugin:")
     * @param options.label - Display label shown in trigger configuration
     * @param options.onMatch - Handler called when trigger pattern matches
     * @param options.configFields - Optional custom configuration fields
     *
     * @example
     * ```typescript
     * api.triggerMacros.register({
     *   id: "customHighlight",
     *   label: "Custom Highlight",
     *   onMatch: (context) => {
     *     const color = context.config.color || "#ff0000";
     *     context.line.color(context.matchRange, api.colors.fromHex(color));
     *   },
     *   configFields: [
     *     { name: "color", type: "text", label: "Color (hex)", defaultValue: "#ff0000" }
     *   ]
     * });
     * ```
     */
    register(options: {
        id: string;
        label: string;
        onMatch: (context: TriggerMacroContext) => void;
        configFields?: MacroConfigField[];
    }): void;
    /**
     * Unregister a previously registered trigger macro
     * @param id - Macro ID (without "plugin:" prefix)
     */
    unregister(id: string): void;
}

/**
 * Settings API - Access character and UI settings
 *
 * Provides read-only access to character settings (scoped to current character)
 * and UI settings (global).
 */

export interface SettingsApi {
    /**
     * Get all character settings
     * @returns Current character settings merged with defaults
     *
     * @example
     * ```typescript
     * const settings = await api.settings.getCharacterSettings();
     * console.log(`Attack command: ${settings.attackCommand}`);
     * console.log(`Guilds: ${settings.guilds?.join(", ")}`);
     * ```
     */
    getCharacterSettings(): Promise<Settings>;
    /**
     * Get a specific character setting
     * @param key - Setting key (e.g., "attackCommand", "guilds", "collectMode")
     * @returns The value of the setting
     *
     * @example
     * ```typescript
     * const guilds = await api.settings.getCharacterSetting("guilds");
     * const attackCommand = await api.settings.getCharacterSetting("attackCommand");
     * ```
     */
    getCharacterSetting<K extends keyof Settings>(key: K): Promise<Settings[K]>;
    /**
     * Get all UI settings
     * @returns Current UI settings merged with defaults
     *
     * @example
     * ```typescript
     * const uiSettings = await api.settings.getUiSettings();
     * console.log(`Font size: ${uiSettings.contentFontSize}`);
     * console.log(`Map position: ${uiSettings.mapPosition}`);
     * ```
     */
    getUiSettings(): Promise<UiSettings>;
    /**
     * Get a specific UI setting
     * @param key - Setting key (e.g., "contentFontSize", "mapPosition", "showButtons")
     * @returns The value of the setting
     *
     * @example
     * ```typescript
     * const fontSize = await api.settings.getUiSetting("contentFontSize");
     * const mapPosition = await api.settings.getUiSetting("mapPosition");
     * ```
     */
    getUiSetting<K extends keyof UiSettings>(key: K): Promise<UiSettings[K]>;
}

/**
 * Combat API - Access combat-related settings and commands
 *
 * Provides access to combat settings like weapon draw commands.
 */

export interface CombatApi {
    /**
     * Draw all weapons using the configured draw weapon command
     *
     * Sends the appropriate command based on character settings
     * (e.g., "dobadz wszystkich broni", "wyciagnij wszystkich broni")
     *
     * @example
     * ```typescript
     * api.combat.drawWeapon();
     * ```
     */
    drawWeapon(): void;
}

/**
 * Location Notes API - Add plugin-contributed notes to locations
 *
 * Plugins can add notes to locations that appear alongside user notes.
 * Plugin notes are read-only for users and displayed with the plugin name.
 */

export interface LocationNotesApi {
    /**
     * Set a note for a location
     *
     * Setting an empty note removes it.
     *
     * @param roomId - Room ID to add note to
     * @param note - Note content (empty string to remove)
     *
     * @example
     * ```typescript
     * // Add a note to room 12345
     * api.locationNotes.set(12345, "Quest NPC here");
     *
     * // Remove the note
     * api.locationNotes.set(12345, "");
     * ```
     */
    set(roomId: number, note: string): void;
    /**
     * Remove a note for a location
     *
     * @param roomId - Room ID to remove note from
     *
     * @example
     * ```typescript
     * api.locationNotes.remove(12345);
     * ```
     */
    remove(roomId: number): void;
    /**
     * Get all plugin notes for a location (from all plugins)
     *
     * @param roomId - Room ID to get notes for
     * @returns Array of plugin notes for the location
     *
     * @example
     * ```typescript
     * const notes = api.locationNotes.get(12345);
     * notes.forEach(n => console.log(`${n.pluginId}: ${n.note}`));
     * ```
     */
    get(roomId: number): PluginLocationNote[];
}

/**
 * Attack Controller API - Execute attacks with proper team coordination
 *
 * Provides methods to attack targets by their object ID, respecting
 * attack mode settings and team coordination (leader commands).
 */

export interface AttackControllerApi {
    /**
     * Attack a target by its object ID
     *
     * When attack mode is "AW" or "AWR" and user is team leader:
     * - "AW": Also marks target as team attack target
     * - "AWR": Marks target and orders team to attack
     *
     * @param id - Object ID of the target
     * @param command - Optional attack command override (uses character setting if not provided)
     *
     * @example
     * ```typescript
     * // Attack object with ID 123
     * api.attackController.attackById(123);
     *
     * // Attack with custom command
     * api.attackController.attackById(123, "kopnij");
     * ```
     */
    attackById(id: number, command?: string): void;
    /**
     * Support the team leader by attacking their target
     *
     * Sends the support command (default: "wesprzyj") and also
     * sends the command targeting the leader's object ID.
     *
     * @param command - Optional support command override (uses character setting if not provided)
     *
     * @example
     * ```typescript
     * // Support the leader
     * api.attackController.support();
     *
     * // Support with custom command
     * api.attackController.support("pomoz");
     * ```
     */
    support(command?: string): void;
    /**
     * Get the current attack command from character settings
     *
     * @returns The configured attack command (e.g., "zabij", "zaatakuj")
     *
     * @example
     * ```typescript
     * const cmd = api.attackController.getAttackCommand();
     * console.log(`Current attack command: ${cmd}`);
     * ```
     */
    getAttackCommand(): string;
    /**
     * Get the current support command from character settings
     *
     * @returns The configured support command (e.g., "wesprzyj")
     *
     * @example
     * ```typescript
     * const cmd = api.attackController.getSupportCommand();
     * console.log(`Current support command: ${cmd}`);
     * ```
     */
    getSupportCommand(): string;
}

/**
 * People API - Manage people database entries
 */

export interface PeopleApi {
    add(entry: {
        name: string;
        description: string;
        guild: string;
    }): void;
    edit(targetKey: string, entry: {
        name: string;
        description: string;
        guild: string;
    }): void;
    remove(eventId: string): void;
    ignore(targetKey: string): void;
    restore(targetKey: string): void;
    markEnemy(targetKey: string): void;
    unmarkEnemy(targetKey: string): void;
    markAlly(targetKey: string): void;
    unmarkAlly(targetKey: string): void;
    setColor(targetKey: string, color: string): void;
    clearColor(targetKey: string): void;
    find(name: string, description: string): PersonListEntry | undefined;
    findByKey(key: string): PersonListEntry | undefined;
    getAll(): PersonListEntry[];
    makeKey(name: string, description: string): string;
}

/**
 * Plugin API Interface
 *
 * This is the main interface that plugins interact with.
 * Provides controlled access to client functionality organized by domain.
 *
 * @example
 * ```typescript
 * export async function init(api: PluginApi): Promise<PluginInfo> {
 *   // Register a trigger
 *   api.triggers.register(/pattern/i, (line, matches) => {
 *     return line.prepend(">> ");
 *   }, "myPlugin");
 *
 *   // Register an alias
 *   api.aliases.register(/^\/cmd$/, () => {
 *     api.output.print("Command executed!", "system");
 *     return true;
 *   });
 *
 *   // Subscribe to events (fully typed!)
 *   api.events.on("mapMove", () => {
 *     console.log("Player moved!");
 *   });
 *
 *   api.events.on("gmcp", (data) => {
 *     console.log("GMCP data:", data.path, data.value);
 *   });
 *
 *   // Get current room
 *   const room = api.map.getRoom();
 *   if (room) console.log(`In ${room.name}`);
 *
 *   // Create colors
 *   const redColor = api.colors.fromHex("#ff0000");
 *   const blueColor = api.colors.fromRgb(0, 128, 255);
 *
 *   // Create a popup (Promise-based)
 *   const popup = await api.ui.createPopup("My Popup", "Hello World!");
 *   console.log("Popup element:", popup.element); // Element is guaranteed to exist
 *
 *   // Listen for close events
 *   popup.onClose(() => {
 *     console.log("Popup was closed!");
 *   });
 *
 *   // Add context menu entry with SVG icon
 *   const menuItem = document.createElement('span');
 *   menuItem.innerHTML = '<svg width="16" height="16">...</svg> Action';
 *   api.ui.addContextMenuEntry(menuItem, () => {
 *     console.log("Context menu action!");
 *   });
 *
 *   // Add popup menu entry with icon
 *   const popupMenuItem = document.createElement('span');
 *   popupMenuItem.innerHTML = '⚙️ Settings';
 *   api.ui.addPopupMenuEntry(popupMenuItem, () => {
 *     console.log("Settings!");
 *   });
 *
 *   return {
 *     name: "My Plugin",
 *     version: "1.0.0"
 *   };
 * }
 * ```
 */

export interface PluginApi {
    /** Trigger management */
    triggers: TriggersApi;
    /** Command alias management */
    aliases: AliasesApi;
    /** Event subscription and emission */
    events: EventsApi;
    /** Map position access */
    map: MapApi;
    /** Output to game window */
    output: OutputApi;
    /** UI helpers */
    ui: UiApi;
    /** Color creation helpers */
    colors: ColorsApi;
    /** Function bind management */
    bind: BindApi;
    /** Team management */
    team: TeamApi;
    /** GMCP data access */
    gmcp: GmcpApi;
    /** Attack queue management */
    attackQueue: AttackQueueApi;
    /** Objects in location */
    objects: ObjectsApi;
    /** Command sending */
    command: CommandApi;
    /** Command hooks - intercept and modify commands before processing */
    commandHooks: CommandHooksApi;
    /** Pretty containers - container formatting and filtering */
    prettyContainers: PrettyContainersApi;
    /** Containers - put and take items from assigned bags */
    containers: ContainersApi;
    /** Magics - magic item patterns */
    magics: MagicsApi;
    /** Magic keys - magic key patterns */
    magicKeys: MagicKeysApi;
    /** Herbs - herb inventory management in bags */
    herbs: HerbsApi;
    /** Object list filters - customize object list entry rendering */
    objectListFilters: ObjectListFiltersApi;
    /** Button macros - register custom button macros */
    buttonMacros: ButtonMacrosApi;
    /** Trigger macros - register custom trigger macros */
    triggerMacros: TriggerMacrosApi;
    /** Settings - access character and UI settings */
    settings: SettingsApi;
    /** Attack controller - execute attacks with team coordination */
    attackController: AttackControllerApi;
    /** Combat - access combat-related settings */
    combat: CombatApi;
    /** Location notes - add plugin-contributed notes to locations */
    locationNotes: LocationNotesApi;
    /** People database - manage people entries */
    people: PeopleApi;
    /**
     * AnsiAwareBuffer class for creating formatted text buffers
     *
     * Use this to create custom formatted output for api.output.print()
     *
     * @example
     * // Create a formatted buffer
     * const buffer = new api.AnsiAwareBuffer("Hello ", api.colors.fromHex('#00ff00'));
     * buffer.append("world!", api.colors.fromHex('#ff0000'));
     * api.output.print(buffer);
     */
    AnsiAwareBuffer: typeof AnsiAwareBuffer;
}

// ============================================================================
// Exports
// ============================================================================

export default PluginApi;
