/**
 * Shape of the build-time "knowledge bundle" that feeds the in-client AI
 * assistant.
 *
 * The bundle is generated by `scripts/build-assistant-kb.ts` (run via
 * `yarn build:assistant-kb`) into `public/assistant-kb.json`. It is deliberately
 * dependency-free and DOM-free so that both the browser client and the LLM
 * proxy (a Cloudflare Worker) can `import type` from here without pulling any
 * runtime code in.
 *
 * Two projections exist over the same bundle, because free-tier providers have
 * wildly different tokens-per-minute budgets:
 *
 * - **lean** (`projectLean`)  — metadata + the compact one-line index + the
 *   proposal schemas. Self-contained: it can be sent as a standalone system
 *   prompt. Target: well under ~10k tokens.
 * - **fat**  (`projectFat`)   — everything, including full documentation
 *   markdown and per-setting detail.
 */

/** Where a setting physically lives. */
export type SettingScope = 'character' | 'ui';

/** The kind of control the stock UI renders for a setting, when known. */
export type SettingControl =
    | 'checkbox'
    | 'select'
    | 'number'
    | 'range'
    | 'color'
    | 'text'
    | 'list'
    | 'complex'
    | 'unknown';

/** One allowed value of an enum-ish setting, with the label the UI shows. */
export interface SettingOption {
    /** Raw value written to storage. */
    value: string | number | boolean;
    /** Polish label as rendered in the settings UI, when one exists. */
    label?: string;
}

/** A single user-facing setting key. */
export interface SettingEntry {
    /**
     * Stable catalog identifier, e.g. `character.settings.shortenExits` or
     * `ui.renderSettings.colorTheme`. It is the key used by
     * `scripts/assistant-kb-overrides.json` and nothing else.
     *
     * **This is not what a proposal carries.** A `settingChange` proposal is
     * validated by `@modules/core/assistant/settingsRegistry`, whose keys are
     * `<storageKey>.<key>` (`settings.shortenExits`,
     * `renderSettings.colorTheme`) — no `character.`/`ui.` prefix. Use
     * `settingProposalKey()` to build the value the validator accepts.
     */
    path: string;
    /** Which storage the value lives in. */
    scope: SettingScope;
    /**
     * localStorage key holding the object that owns this field
     * (`settings`, `uiSettings`, `renderSettings`, `mapSettings`, …).
     */
    storageKey: string;
    /** Field name inside that object. */
    key: string;
    /** TypeScript type text as written in the source interface. */
    type: string;
    /** True when the source declares the property optional (`?`). */
    optional: boolean;
    /** Default value, or `null` when it could not be evaluated statically. */
    default: unknown;
    /** Source text of the default when it is not a static literal. */
    defaultExpression?: string;
    /** Allowed values, when the type is a literal union or the UI is a select. */
    options?: SettingOption[];
    /** Numeric bounds recovered from the UI control. */
    min?: number;
    max?: number;
    step?: number;
    /** Polish label recovered from the settings UI. */
    label?: string;
    /**
     * Where the user navigates to change it, e.g.
     * `Ustawienia UI → Ogólne → Wygląd`. Absent when the key is not exposed.
     */
    uiLocation?: string;
    /** Control the stock UI renders. */
    control: SettingControl;
    /** Extra prose hint (hand-maintained override). */
    note?: string;
    /** False when no control in the stock settings UI writes this key. */
    exposedInUi: boolean;
    /** Where the information came from — useful when auditing drift. */
    sources: string[];
}

/** A client-registered command/alias the user can type. */
export interface CommandEntry {
    /** Human-facing command token, e.g. `/prowadz`. */
    name: string;
    /** The exact regex the client matches against the typed line. */
    pattern: string;
    /** Argument hint recovered from docs, e.g. `/czas imperium <godzina>`. */
    usage?: string;
    /** Polish description, from the docs tables or the override file. */
    description?: string;
    /** Source module that registers it, relative to the repo root. */
    source: string;
    /** Doc file the description came from. */
    documentedIn?: string;
}

/** One entry of `SUPPORTED_EVENTS` from `@client/scripts/userTriggers`. */
export interface EventEntry {
    id: string;
    label: string;
    category: string;
}

/** A JSON-shaped schema the assistant is allowed to propose. */
export interface ProposalSchema {
    /** Schema id, e.g. `UserAlias`. */
    name: string;
    /** Polish/English prose describing when to use it. */
    description: string;
    /** The TypeScript source of the interface(s), verbatim from the repo. */
    typescript: string;
    /** Field-by-field notes the model needs to get it right first time. */
    fields: { name: string; type: string; required: boolean; note?: string }[];
    /** Worked examples — valid JSON payloads plus what they achieve. */
    examples: { description: string; value: unknown }[];
    /** Hard rules (validation constraints, gotchas). */
    rules: string[];
}

/**
 * Every `kind` a proposal may carry, and the ONLY source of that list outside
 * the validator itself.
 *
 * The names are exactly `ProposalKind` in
 * `@modules/core/assistant/proposalValidator` — the module that gates writes to
 * the user's storage. It is the authority; the generator, the prompt schemas and
 * the Worker all follow it. Because `@modules` pulls in `@client` (and therefore
 * a browser-shaped dependency tree) the Worker cannot import the validator, so
 * the list is restated here, in the one file that is deliberately dependency-
 * free and DOM-free — and
 * `test/shared/assistant/proposalSchemaAlignment.test.ts` fails the build if the
 * two ever disagree.
 */
export const PROPOSAL_KINDS = ['settingChange', 'alias', 'trigger', 'bind'] as const;

export type ProposalKindName = (typeof PROPOSAL_KINDS)[number];

/**
 * Proposal schemas, keyed by the `kind` they document.
 *
 * Four of the keys are `ProposalKindName`s. `userMacro` is deliberately not one:
 * a macro is never proposed on its own, it only ever appears inside a
 * `trigger`'s `macros` array, and the key is named so that the difference is
 * visible at a glance.
 */
export interface SchemaCatalog extends Record<ProposalKindName, ProposalSchema> {
    alias: ProposalSchema;
    trigger: ProposalSchema;
    userMacro: ProposalSchema;
    bind: ProposalSchema;
    settingChange: ProposalSchema;
}

/**
 * Schema as carried by the lean projection: the verbatim TypeScript is dropped
 * because `fields` already encodes name/type/required, and the source text is
 * the single most expensive part of the prompt. The fat bundle keeps it.
 */
export type LeanProposalSchema = Omit<ProposalSchema, 'typescript'>;

export type LeanSchemaCatalog = Record<keyof SchemaCatalog, LeanProposalSchema>;

/** A user-facing documentation page. */
export interface DocEntry {
    /** File name, e.g. `NAVIGATION.md`. */
    id: string;
    /** Repo-relative path. */
    path: string;
    /** Top-level `#` heading. */
    title: string;
    /** All `##`/`###` headings, in order. */
    headings: string[];
    /** Rough token estimate for this page alone. */
    tokens: number;
    /** Full markdown. */
    content: string;
}

/** Compact, self-contained table of contents — the "lean" payload. */
export interface KnowledgeIndex {
    /** How to read the compact lines below. Send this verbatim to the model. */
    format: string[];
    /**
     * Location legend: `P1 = Menu (⋮) → … → Sekcja`. Settings lines reference
     * these by id instead of repeating the whole navigation path.
     */
    panels: string[];
    /**
     * Settings, grouped. `## <scope>.<storageKey>.*` starts a group; the lines
     * that follow are `key | label | P# | type-or-enum | default`.
     */
    settings: string[];
    /** One line per command: `name — description`. */
    commands: string[];
    /** One line per trigger event: `id — label (category)`. */
    events: string[];
    /** Doc pages with their top-level headings, but no body. */
    docs: { id: string; title: string; headings: string[]; tokens: number }[];
}

export interface KnowledgeBundleStats {
    settings: number;
    settingsWithLabels: number;
    commands: number;
    commandsWithDescriptions: number;
    events: number;
    docs: number;
    leanChars: number;
    leanTokens: number;
    fatChars: number;
    fatTokens: number;
}

export interface KnowledgeBundle {
    /** Schema version of this file format. Bump on breaking shape changes. */
    formatVersion: number;
    /** Content hash over everything but `generatedAt` — safe to cache on. */
    version: string;
    /** ISO timestamp of the generating run. */
    generatedAt: string;
    /** Lean projection payload. */
    index: KnowledgeIndex;
    /** Proposal schemas — included in BOTH projections. */
    schemas: SchemaCatalog;
    settings: SettingEntry[];
    commands: CommandEntry[];
    events: EventEntry[];
    docs: DocEntry[];
    /** Keys the generator could not resolve from source; needs a human. */
    gaps: string[];
    stats: KnowledgeBundleStats;
}

/** Everything the lean prompt carries. */
export interface LeanKnowledgeBundle {
    formatVersion: number;
    version: string;
    generatedAt: string;
    index: KnowledgeIndex;
    schemas: LeanSchemaCatalog;
}

export const KB_FORMAT_VERSION = 1;

/** Public path the generated bundle is served from. */
export const KB_PUBLIC_PATH = '/assistant-kb.json';

/**
 * Rough token estimate. Good enough for budgeting against provider TPM limits;
 * every provider tokenizes differently anyway.
 */
export function estimateTokens(text: string): number {
    return Math.ceil(text.length / 4);
}

/**
 * The key a `settingChange` proposal must carry for this entry.
 *
 * `SettingEntry.path` carries a `character.`/`ui.` scope prefix that the
 * validator's registry does not use, so composing a proposal from `path`
 * produces an `unknownSettingKey` rejection every single time. The registry key
 * is `<storageKey>.<field>`, which is exactly this.
 */
export function settingProposalKey(entry: Pick<SettingEntry, 'storageKey' | 'key'>): string {
    return `${entry.storageKey}.${entry.key}`;
}

/** The small projection: index + schemas, no doc bodies, no per-setting detail. */
export function projectLean(bundle: KnowledgeBundle): LeanKnowledgeBundle {
    const schemas = {} as LeanSchemaCatalog;
    for (const name of Object.keys(bundle.schemas) as (keyof SchemaCatalog)[]) {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars -- destructured to drop the field
        const { typescript, ...rest } = bundle.schemas[name];
        schemas[name] = rest;
    }
    return {
        formatVersion: bundle.formatVersion,
        version: bundle.version,
        generatedAt: bundle.generatedAt,
        index: bundle.index,
        schemas,
    };
}

/** The full projection. Identity today; kept as a seam for future trimming. */
export function projectFat(bundle: KnowledgeBundle): KnowledgeBundle {
    return bundle;
}
