/**
 * Polish number words to numeric values converter
 * Used across multiple scripts to parse Polish number words from MUD output
 */

/**
 * Mapping of Polish number words (with various grammatical cases) to numeric values
 */
export const polishNumberWords: Record<string, number> = {
    'jeden': 1, 'jedna': 1, 'jedno': 1,
    'jednego': 1,
    'jednej': 1,
    'dwa': 2, 'dwie': 2, 'dwaj': 2,
    'dwoch': 2,
    'trzy': 3, 'trzej': 3,
    'trzech': 3,
    'cztery': 4, 'czterej': 4,
    'czterech': 4,
    'piec': 5,
    'pieciu': 5,
    'szesc': 6,
    'szesciu': 6,
    'siedem': 7,
    'siedmiu': 7,
    'osiem': 8,
    'osmiu': 8,
    'dziewiec': 9,
    'dziewieciu': 9,
    'dziesiec': 10,
    'dziesieciu': 10,
    'jedenascie': 11,
    'jedenastu': 11,
    'dwanascie': 12,
    'dwunastu': 12,
    'trzynascie': 13,
    'trzynastu': 13,
    'czternascie': 14,
    'czternastu': 14,
    'pietnascie': 15,
    'pietnastu': 15,
    'szesnascie': 16,
    'szesnastu': 16,
    'siedemnascie': 17,
    'siedemnastu': 17,
    'osiemnascie': 18,
    'osiemnastu': 18,
    'dziewietnascie': 19,
    'dziewietnastu': 19,
    'dwadziescia': 20,
    'dwudziestu': 20,
    'dwadziescia jeden': 21, 'dwadziescia jedna': 21,
    'dwudziestu jeden': 21,
    'dwadziescia dwa': 22, 'dwadziescia dwie': 22,
    'dwudziestu dwoch': 22,
    'dwadziescia trzy': 23,
    'dwudziestu trzech': 23,
    'dwadziescia cztery': 24,
    'dwudziestu czterech': 24,
    'dwadziescia piec': 25,
    'dwudziestu pieciu': 25,
    'dwadziescia szesc': 26,
    'dwudziestu szesciu': 26,
    'dwadziescia siedem': 27,
    'dwudziestu siedmiu': 27,
    'dwadziescia osiem': 28,
    'dwudziestu osmiu': 28,
    'dwadziescia dziewiec': 29,
    'dwudziestu dziewieciu': 29,
    'trzydziesci': 30,
    'trzydziestu': 30,
    'trzydziesci jeden': 31, 'trzydziesci jedna': 31,
    'trzydziestu jeden': 31,
    'trzydziesci dwa': 32, 'trzydziesci dwie': 32,
    'trzydziestu dwoch': 32,
    'trzydziesci trzy': 33,
    'trzydziestu trzech': 33,
    'trzydziesci cztery': 34,
    'trzydziestu czterech': 34,
    'trzydziesci piec': 35,
    'trzydziestu pieciu': 35,
    'trzydziesci szesc': 36,
    'trzydziestu szesciu': 36,
    'trzydziesci siedem': 37,
    'trzydziestu siedmiu': 37,
    'trzydziesci osiem': 38,
    'trzydziestu osmiu': 38,
    'trzydziesci dziewiec': 39,
    'trzydziestu dziewieciu': 39,
    'czterdziesci': 40,
    'czterdziestu': 40,
    'czterdziesci jeden': 41, 'czterdziesci jedna': 41,
    'czterdziestu jeden': 41,
    'czterdziesci dwa': 42, 'czterdziesci dwie': 42,
    'czterdziestu dwoch': 42,
    'czterdziesci trzy': 43,
    'czterdziestu trzech': 43,
    'czterdziesci cztery': 44,
    'czterdziestu czterech': 44,
    'czterdziesci piec': 45,
    'czterdziestu pieciu': 45,
    'czterdziesci szesc': 46,
    'czterdziestu szesciu': 46,
    'czterdziesci siedem': 47,
    'czterdziestu siedmiu': 47,
    'czterdziesci osiem': 48,
    'czterdziestu osmiu': 48,
    'czterdziesci dziewiec': 49,
    'czterdziestu dziewieciu': 49,
    'piecdziesiat': 50,
    'piecdziesieciu': 50,
    'piecdziesiat jeden': 51, 'piecdziesiat jedna': 51,
    'piecdziesieciu jeden': 51,
    'piecdziesiat dwa': 52, 'piecdziesiat dwie': 52,
    'piecdziesieciu dwoch': 52,
    'piecdziesiat trzy': 53,
    'piecdziesieciu trzech': 53,
    'piecdziesiat cztery': 54,
    'piecdziesieciu czterech': 54,
    'piecdziesiat piec': 55,
    'piecdziesieciu pieciu': 55,
    'piecdziesiat szesc': 56,
    'piecdziesieciu szesciu': 56,
    'piecdziesiat siedem': 57,
    'piecdziesieciu siedmiu': 57,
    'piecdziesiat osiem': 58,
    'piecdziesieciu osmiu': 58,
    'piecdziesiat dziewiec': 59,
    'piecdziesieciu dziewieciu': 59,
    'szescdziesiat': 60,
    'szescdziesieciu': 60,
    'szescdziesiat jeden': 61, 'szescdziesiat jedna': 61,
    'szescdziesieciu jeden': 61,
    'szescdziesiat dwa': 62, 'szescdziesiat dwie': 62,
    'szescdziesieciu dwoch': 62,
    'szescdziesiat trzy': 63,
    'szescdziesieciu trzech': 63,
    'szescdziesiat cztery': 64,
    'szescdziesieciu czterech': 64,
    'szescdziesiat piec': 65,
    'szescdziesieciu pieciu': 65,
    'szescdziesiat szesc': 66,
    'szescdziesieciu szesciu': 66,
    'szescdziesiat siedem': 67,
    'szescdziesieciu siedmiu': 67,
    'szescdziesiat osiem': 68,
    'szescdziesieciu osmiu': 68,
    'szescdziesiat dziewiec': 69,
    'szescdziesieciu dziewieciu': 69,
    'siedemdziesiat': 70,
    'siedemdziesieciu': 70,
    'siedemdziesiat jeden': 71, 'siedemdziesiat jedna': 71,
    'siedemdziesieciu jeden': 71,
    'siedemdziesiat dwa': 72, 'siedemdziesiat dwie': 72,
    'siedemdziesieciu dwoch': 72,
    'siedemdziesiat trzy': 73,
    'siedemdziesieciu trzech': 73,
    'siedemdziesiat cztery': 74,
    'siedemdziesieciu czterech': 74,
    'siedemdziesiat piec': 75,
    'siedemdziesieciu pieciu': 75,
    'siedemdziesiat szesc': 76,
    'siedemdziesieciu szesciu': 76,
    'siedemdziesiat siedem': 77,
    'siedemdziesieciu siedmiu': 77,
    'siedemdziesiat osiem': 78,
    'siedemdziesieciu osmiu': 78,
    'siedemdziesiat dziewiec': 79,
    'siedemdziesieciu dziewieciu': 79,
    'osiemdziesiat': 80,
    'osiemdziesieciu': 80,
    'osiemdziesiat jeden': 81, 'osiemdziesiat jedna': 81,
    'osiemdziesieciu jeden': 81,
    'osiemdziesiat dwa': 82, 'osiemdziesiat dwie': 82,
    'osiemdziesieciu dwoch': 82,
    'osiemdziesiat trzy': 83,
    'osiemdziesieciu trzech': 83,
    'osiemdziesiat cztery': 84,
    'osiemdziesieciu czterech': 84,
    'osiemdziesiat piec': 85,
    'osiemdziesieciu pieciu': 85,
    'osiemdziesiat szesc': 86,
    'osiemdziesieciu szesciu': 86,
    'osiemdziesiat siedem': 87,
    'osiemdziesieciu siedmiu': 87,
    'osiemdziesiat osiem': 88,
    'osiemdziesieciu osmiu': 88,
    'osiemdziesiat dziewiec': 89,
    'osiemdziesieciu dziewieciu': 89,
    'dziewiecdziesiat': 90,
    'dziewiecdziesieciu': 90,
    'dziewiecdziesiat jeden': 91, 'dziewiecdziesiat jedna': 91,
    'dziewiecdziesieciu jeden': 91,
    'dziewiecdziesiat dwa': 92, 'dziewiecdziesiat dwie': 92,
    'dziewiecdziesieciu dwoch': 92,
    'dziewiecdziesiat trzy': 93,
    'dziewiecdziesieciu trzech': 93,
    'dziewiecdziesiat cztery': 94,
    'dziewiecdziesieciu czterech': 94,
    'dziewiecdziesiat piec': 95,
    'dziewiecdziesieciu pieciu': 95,
    'dziewiecdziesiat szesc': 96,
    'dziewiecdziesieciu szesciu': 96,
    'dziewiecdziesiat siedem': 97,
    'dziewiecdziesieciu siedmiu': 97,
    'dziewiecdziesiat osiem': 98,
    'dziewiecdziesieciu osmiu': 98,
    'dziewiecdziesiat dziewiec': 99,
    'dziewiecdziesieciu dziewieciu': 99,
    // collective numerals (liczebniki zbiorowe): nominative
    'dwoje': 2,
    'troje': 3,
    'czworo': 4,
    'piecioro': 5,
    'szescioro': 6,
    'siedmioro': 7,
    'osmioro': 8,
    'dziewiecioro': 9,
    'dziesiecioro': 10,
    // genitive
    'dwojga': 2,
    'trojga': 3,
    'czworga': 4,
    'pieciorga': 5,
    'szesciorga': 6,
    'siedmiorga': 7,
    'osmiorga': 8,
    'dziewieciorga': 9,
    'dziesieciorga': 10,
    // dative/locative
    'dwojgu': 2,
    'trojgu': 3,
    'czworgu': 4,
    'pieciorgu': 5,
    'szesciorgu': 6,
    'siedmiorgu': 7,
    'osmiorgu': 8,
    'dziewieciorgu': 9,
    'dziesieciorgu': 10,
    // instrumental
    'dwojgiem': 2,
    'trojgiem': 3,
    'czworgiem': 4,
    'pieciorgiem': 5,
    'szesciorgiem': 6,
    'siedmiorgiem': 7,
    'osmiorgiem': 8,
    'dziewieciorgiem': 9,
    'dziesieciorgiem': 10
};

/**
 * Create a regex pattern that matches all Polish number words
 * Sorted by length (descending) to match longer phrases first
 */
export const polishNumberPattern = Object.keys(polishNumberWords)
    .sort((a, b) => b.length - a.length)
    .map(num => num.replace(/\s+/g, '\\s+'))
    .join('|');

/**
 * Convert Polish number word to integer
 * Handles both numeric strings and Polish word forms
 *
 * @param word - The Polish number word or numeric string
 * @returns The numeric value, or 0 if not recognized
 *
 * @example
 * polishWordToNumber('trzy') // returns 3
 * polishWordToNumber('dwadziescia jeden') // returns 21
 * polishWordToNumber('42') // returns 42
 * polishWordToNumber('nieznane') // returns 0
 */
export function polishWordToNumber(word: string): number {
    const trimmed = word.trim().toLowerCase();

    // Handle numeric strings directly
    if (/^\d+$/.test(trimmed)) {
        return parseInt(trimmed, 10);
    }

    // Normalize whitespace for compound numbers
    const normalized = trimmed.replace(/\s+/g, ' ');

    return polishNumberWords[normalized] ?? 0;
}
