// UI settings type definitions live in `@shared/uiSettingsTypes` (UI-neutral) so
// lower layers can reference them without importing `@web`. They are re-exported
// here to preserve the historical `@web/defaultUiSettings` import path.
export type {
    SoundCategories,
    MapPosition,
    UiFontSelection,
    MapRoomShape,
    MapHighlightShape,
    PathFindingAlgorithm,
    ColorTheme,
    FooterComponentConfig,
    UiSettings,
} from '@shared/uiSettingsTypes';
import type { FooterComponentConfig, UiSettings } from '@shared/uiSettingsTypes';

export const defaultFooterComponents: FooterComponentConfig[] = [
    { id: 'clock-display', visible: true, order: 0 },
    { id: 'transport-timer', visible: true, order: 1 },
    { id: 'lamp-timer', visible: true, order: 2 },
    { id: 'pipe-status', visible: true, order: 3 },
    { id: 'break-item-warning', visible: true, order: 4 },
    { id: 'mail-status', visible: true, order: 5 },
    { id: 'package-status', visible: true, order: 6 },
    { id: 'weapon-state', visible: true, order: 7 },
    { id: 'attack-mode', visible: true, order: 8 },
    { id: 'release-guard-timer', visible: true, order: 9 },
    { id: 'zask-timer', visible: true, order: 10 },
    { id: 'order-timer', visible: true, order: 11 },
    { id: 'combat-timer', visible: true, order: 12 },
    { id: 'world-destruction-timer', visible: true, order: 13 },
    { id: 'team-panel', visible: true, order: 14 },
];

export const defaultUiSettings: UiSettings = {
    contentFontSize: 0.775,
    objectsFontSize: 0.6,
    mapScale: 0.30,
    showButtons: true,
    hapticFeedback: true,
    mapHeight: typeof window !== 'undefined' && window.innerWidth < 768 ? 25 : 30,
    mapPosition: 'top-overlay',
    emojiLabels: false,
    fightTitleIcon: true,
    xtermPalette: 'arkadia',
    footerMode: 0,
    explorationMode: false,
    instantMove: true,
    highlightCurrentRoom: true,
    labelRenderMode: 'data',
    transparentLabels: true,
    outputBackground: '#242424',
    clearInputOnSend: false,
    fontFamily: 'default',
    customFontUrl: '',
    customFontFamily: '',
    autoLowercaseCommands: false,
    customBeepSoundKey: undefined,
    mapRoomSize: 0.6,
    mapLineWidth: 0.025,
    mapPlayerMarkerStrokeColor: '#00e5b2',
    mapPlayerMarkerStrokeAlpha: 1,
    mapPlayerMarkerFillColor: '#00e5b2',
    mapPlayerMarkerFillAlpha: 0,
    mapPlayerMarkerStrokeWidth: 0.1,
    mapPlayerMarkerSizeFactor: 1.7,
    mapPlayerMarkerDashEnabled: true,
    mapHighlightStrokeAlpha: 1,
    mapHighlightFillAlpha: 0,
    mapHighlightStrokeWidth: 0.1,
    mapHighlightSizeFactor: 1.425,
    mapHighlightDashEnabled: true,
    mapHighlightShape: 'match',
    mapRoomShape: 'rectangle',
    mapBackgroundColor: '#000000',
    mapLineColor: '#e1ffe1',
    pathFindingAlgorithm: 'dijkstra',
    objectContextMenuCommands: ['ob', 'ocen', 'zapros', 'wskaz'],
    footerComponents: defaultFooterComponents,
    keepMultibindsVisible: false,
    wakeLock: true,
    commandEcho: true,
    outputBottomPadding: 0,
    outputMaxElements: 1000,
    teamNumberingMode: 'letters',
    drinkableAsFunctionalBind: true,
    objectListBackgroundColor: '#000000',
    objectListBackgroundAlpha: 0.4,
    alwaysVisibleBars: [],
    barOrder: ['hp', 'fatigue', 'stuffed', 'encumbrance', 'soaked', 'mana', 'improve', 'form', 'intox', 'headache', 'panic'],
    colorTheme: 'default',
    soundCategories: {},
    showTimestamps: false,
};
