name: Deploy web-client
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  workflow_dispatch:


permissions:
  pages: write
  id-token: write

jobs:
  pages:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.ref }}
      - run: yarn install
      - run: yarn --cwd web-client install && yarn --cwd web-client build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web-client/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
