name: Test
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: .cache/ms-playwright
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Run unit tests
            command: yarn test
          - name: Build project
            command: yarn build
          - name: Run e2e tests
            command: yarn test:e2e --reporter=line
            install_browsers: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('package.json', 'yarn.lock') }}
          restore-keys: |
            key: ${{ runner.os }}-dependencies-
      - name: Cache Playwright browsers
        if: matrix.install_browsers == true
        uses: actions/cache@v4
        with:
          path: .cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install Playwright browsers
        if: matrix.install_browsers == true
        run: yarn playwright install --with-deps chromium
      - name: ${{ matrix.name }}
        env:
          CI: '1'
        run: ${{ matrix.command }}
